#postgres driver
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arbook
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /
      suffix: .html
#server
server:
  port: 8989
  servlet:
    context-path: /arbook



