#postgres driver
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arbook
    username: postgres
    password: postgres
#server
server:
  port: 8989
  servlet:
    context-path: /arbook
mybatis:
  mapper-locations: classpath:mapper/*.xml


