package com.alva.arbook.dao;

import com.alva.arbook.entity.DataTypePrivileges;
import java.util.List;

public interface DataTypePrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_type_privileges
     *
     * @mbg.generated
     */
    int insert(DataTypePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_type_privileges
     *
     * @mbg.generated
     */
    List<DataTypePrivileges> selectAll();
}