package com.alva.arbook.dao;

import com.alva.arbook.entity.Domains;
import java.util.List;

public interface DomainsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbg.generated
     */
    int insert(Domains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbg.generated
     */
    List<Domains> selectAll();
}