package com.alva.arbook.dao;

import com.alva.arbook.entity.ElementTypes;
import java.util.List;

public interface ElementTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_types
     *
     * @mbg.generated
     */
    int insert(ElementTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_types
     *
     * @mbg.generated
     */
    List<ElementTypes> selectAll();
}