package com.alva.arbook.dao;

import com.alva.arbook.entity.ForeignDataWrappers;
import java.util.List;

public interface ForeignDataWrappersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_data_wrappers
     *
     * @mbg.generated
     */
    int insert(ForeignDataWrappers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_data_wrappers
     *
     * @mbg.generated
     */
    List<ForeignDataWrappers> selectAll();
}