package com.alva.arbook.dao;

import com.alva.arbook.entity.PgAggregate;
import java.util.List;

public interface PgAggregateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_aggregate
     *
     * @mbg.generated
     */
    int insert(PgAggregate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_aggregate
     *
     * @mbg.generated
     */
    List<PgAggregate> selectAll();
}