package com.alva.arbook.dao;

import com.alva.arbook.entity.PgAvailableExtensionVersions;
import java.util.List;

public interface PgAvailableExtensionVersionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_available_extension_versions
     *
     * @mbg.generated
     */
    int insert(PgAvailableExtensionVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_available_extension_versions
     *
     * @mbg.generated
     */
    List<PgAvailableExtensionVersions> selectAll();
}