package com.alva.arbook.dao;

import com.alva.arbook.entity.PgAvailableExtensions;
import java.util.List;

public interface PgAvailableExtensionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_available_extensions
     *
     * @mbg.generated
     */
    int insert(PgAvailableExtensions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_available_extensions
     *
     * @mbg.generated
     */
    List<PgAvailableExtensions> selectAll();
}