package com.alva.arbook.dao;

import com.alva.arbook.entity.PgConfig;
import java.util.List;

public interface PgConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_config
     *
     * @mbg.generated
     */
    int insert(PgConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_config
     *
     * @mbg.generated
     */
    List<PgConfig> selectAll();
}