package com.alva.arbook.dao;

import com.alva.arbook.entity.PgCursors;
import java.util.List;

public interface PgCursorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_cursors
     *
     * @mbg.generated
     */
    int insert(PgCursors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_cursors
     *
     * @mbg.generated
     */
    List<PgCursors> selectAll();
}