package com.alva.arbook.dao;

import com.alva.arbook.entity.PgEnum;
import java.util.List;

public interface PgEnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_enum
     *
     * @mbg.generated
     */
    int insert(PgEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_enum
     *
     * @mbg.generated
     */
    List<PgEnum> selectAll();
}