package com.alva.arbook.dao;

import com.alva.arbook.entity.PgForeignTable;
import java.util.List;

public interface PgForeignTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_foreign_table
     *
     * @mbg.generated
     */
    int insert(PgForeignTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_foreign_table
     *
     * @mbg.generated
     */
    List<PgForeignTable> selectAll();
}