package com.alva.arbook.dao;

import com.alva.arbook.entity.PgForeignTableColumns;
import java.util.List;

public interface PgForeignTableColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_table_columns
     *
     * @mbg.generated
     */
    int insert(PgForeignTableColumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_table_columns
     *
     * @mbg.generated
     */
    List<PgForeignTableColumns> selectAll();
}