package com.alva.arbook.dao;

import com.alva.arbook.entity.PgForeignDataWrappers;
import java.util.List;

public interface PgForeignDataWrappersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_data_wrappers
     *
     * @mbg.generated
     */
    int insert(PgForeignDataWrappers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_data_wrappers
     *
     * @mbg.generated
     */
    List<PgForeignDataWrappers> selectAll();
}