package com.alva.arbook.dao;

import com.alva.arbook.entity.PgForeignTables;
import java.util.List;

public interface PgForeignTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_tables
     *
     * @mbg.generated
     */
    int insert(PgForeignTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_tables
     *
     * @mbg.generated
     */
    List<PgForeignTables> selectAll();
}