package com.alva.arbook.dao;

import com.alva.arbook.entity.PgMatviews;
import java.util.List;

public interface PgMatviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_matviews
     *
     * @mbg.generated
     */
    int insert(PgMatviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_matviews
     *
     * @mbg.generated
     */
    List<PgMatviews> selectAll();
}