package com.alva.arbook.dao;

import com.alva.arbook.entity.PgNamespace;
import java.util.List;

public interface PgNamespaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_namespace
     *
     * @mbg.generated
     */
    int insert(PgNamespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_namespace
     *
     * @mbg.generated
     */
    List<PgNamespace> selectAll();
}