package com.alva.arbook.dao;

import com.alva.arbook.entity.PgPolicy;
import java.util.List;

public interface PgPolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_policy
     *
     * @mbg.generated
     */
    int insert(PgPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_policy
     *
     * @mbg.generated
     */
    List<PgPolicy> selectAll();
}