package com.alva.arbook.dao;

import com.alva.arbook.entity.PgPreparedXacts;
import java.util.List;

public interface PgPreparedXactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_prepared_xacts
     *
     * @mbg.generated
     */
    int insert(PgPreparedXacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_prepared_xacts
     *
     * @mbg.generated
     */
    List<PgPreparedXacts> selectAll();
}