package com.alva.arbook.dao;

import com.alva.arbook.entity.PgReplicationOriginStatus;
import java.util.List;

public interface PgReplicationOriginStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_replication_origin_status
     *
     * @mbg.generated
     */
    int insert(PgReplicationOriginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_replication_origin_status
     *
     * @mbg.generated
     */
    List<PgReplicationOriginStatus> selectAll();
}