package com.alva.arbook.dao;

import com.alva.arbook.entity.PgSequences;
import java.util.List;

public interface PgSequencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_sequences
     *
     * @mbg.generated
     */
    int insert(PgSequences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_sequences
     *
     * @mbg.generated
     */
    List<PgSequences> selectAll();
}