package com.alva.arbook.dao;

import com.alva.arbook.entity.PgSeclabel;
import java.util.List;

public interface PgSeclabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_seclabel
     *
     * @mbg.generated
     */
    int insert(PgSeclabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_seclabel
     *
     * @mbg.generated
     */
    List<PgSeclabel> selectAll();
}