package com.alva.arbook.dao;

import com.alva.arbook.entity.PgSeclabels;
import java.util.List;

public interface PgSeclabelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_seclabels
     *
     * @mbg.generated
     */
    int insert(PgSeclabels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_seclabels
     *
     * @mbg.generated
     */
    List<PgSeclabels> selectAll();
}