package com.alva.arbook.dao;

import com.alva.arbook.entity.PgShseclabel;
import java.util.List;

public interface PgShseclabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_shseclabel
     *
     * @mbg.generated
     */
    int insert(PgShseclabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_shseclabel
     *
     * @mbg.generated
     */
    List<PgShseclabel> selectAll();
}