package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatDatabaseConflicts;
import java.util.List;

public interface PgStatDatabaseConflictsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_database_conflicts
     *
     * @mbg.generated
     */
    int insert(PgStatDatabaseConflicts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_database_conflicts
     *
     * @mbg.generated
     */
    List<PgStatDatabaseConflicts> selectAll();
}