package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatWalReceiver;
import java.util.List;

public interface PgStatWalReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_wal_receiver
     *
     * @mbg.generated
     */
    int insert(PgStatWalReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_wal_receiver
     *
     * @mbg.generated
     */
    List<PgStatWalReceiver> selectAll();
}