package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatioAllSequences;
import java.util.List;

public interface PgStatioAllSequencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_sequences
     *
     * @mbg.generated
     */
    int insert(PgStatioAllSequences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_sequences
     *
     * @mbg.generated
     */
    List<PgStatioAllSequences> selectAll();
}