package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatioUserIndexes;
import java.util.List;

public interface PgStatioUserIndexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_user_indexes
     *
     * @mbg.generated
     */
    int insert(PgStatioUserIndexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_user_indexes
     *
     * @mbg.generated
     */
    List<PgStatioUserIndexes> selectAll();
}