package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatioAllIndexes;
import java.util.List;

public interface PgStatioAllIndexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_indexes
     *
     * @mbg.generated
     */
    int insert(PgStatioAllIndexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_indexes
     *
     * @mbg.generated
     */
    List<PgStatioAllIndexes> selectAll();
}