package com.alva.arbook.dao;

import com.alva.arbook.entity.PgStatioAllTables;
import java.util.List;

public interface PgStatioAllTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_tables
     *
     * @mbg.generated
     */
    int insert(PgStatioAllTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_statio_all_tables
     *
     * @mbg.generated
     */
    List<PgStatioAllTables> selectAll();
}