package com.alva.arbook.dao;

import com.alva.arbook.entity.PgTimezoneAbbrevs;
import java.util.List;

public interface PgTimezoneAbbrevsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_timezone_abbrevs
     *
     * @mbg.generated
     */
    int insert(PgTimezoneAbbrevs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_timezone_abbrevs
     *
     * @mbg.generated
     */
    List<PgTimezoneAbbrevs> selectAll();
}