package com.alva.arbook.dao;

import com.alva.arbook.entity.PgTsConfig;
import java.util.List;

public interface PgTsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_ts_config
     *
     * @mbg.generated
     */
    int insert(PgTsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_ts_config
     *
     * @mbg.generated
     */
    List<PgTsConfig> selectAll();
}