package com.alva.arbook.dao;

import com.alva.arbook.entity.PgUserMapping;
import java.util.List;

public interface PgUserMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_user_mapping
     *
     * @mbg.generated
     */
    int insert(PgUserMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_user_mapping
     *
     * @mbg.generated
     */
    List<PgUserMapping> selectAll();
}