package com.alva.arbook.dao;

import com.alva.arbook.entity.RoleRoutineGrants;
import java.util.List;

public interface RoleRoutineGrantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routine_grants
     *
     * @mbg.generated
     */
    int insert(RoleRoutineGrants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routine_grants
     *
     * @mbg.generated
     */
    List<RoleRoutineGrants> selectAll();
}