package com.alva.arbook.dao;

import com.alva.arbook.entity.RoleColumnGrants;
import java.util.List;

public interface RoleColumnGrantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_column_grants
     *
     * @mbg.generated
     */
    int insert(RoleColumnGrants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_column_grants
     *
     * @mbg.generated
     */
    List<RoleColumnGrants> selectAll();
}