package com.alva.arbook.dao;

import com.alva.arbook.entity.RoleUdtGrants;
import java.util.List;

public interface RoleUdtGrantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_udt_grants
     *
     * @mbg.generated
     */
    int insert(RoleUdtGrants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_udt_grants
     *
     * @mbg.generated
     */
    List<RoleUdtGrants> selectAll();
}