package com.alva.arbook.dao;

import com.alva.arbook.entity.Routines;
import java.util.List;

public interface RoutinesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routines
     *
     * @mbg.generated
     */
    int insert(Routines record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table routines
     *
     * @mbg.generated
     */
    List<Routines> selectAll();
}