package com.alva.arbook.dao;

import com.alva.arbook.entity.SqlParts;
import java.util.List;

public interface SqlPartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_parts
     *
     * @mbg.generated
     */
    int insert(SqlParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_parts
     *
     * @mbg.generated
     */
    List<SqlParts> selectAll();
}