package com.alva.arbook.dao;

import com.alva.arbook.dto.TextbookQueryDTO;
import com.alva.arbook.entity.SysTextbookT;
import com.alva.arbook.vo.TextbookVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysTextbookTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_textbook_t
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String szId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_textbook_t
     *
     * @mbg.generated
     */
    int insert(SysTextbookT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_textbook_t
     *
     * @mbg.generated
     */
    SysTextbookT selectByPrimaryKey(String szId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_textbook_t
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysTextbookT record);

    List<SysTextbookT> selectByCustom(TextbookQueryDTO textbookQueryDTO);

    Long countByCustomQuery(TextbookQueryDTO textbookQueryDTO);

    List<String> selectDistinctSection();

    List<String> selectDistinctGrade();

    int editBook(SysTextbookT sysTextbookT);
}