package com.alva.arbook.dao;

import com.alva.arbook.entity.TablePrivileges;
import java.util.List;

public interface TablePrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_privileges
     *
     * @mbg.generated
     */
    int insert(TablePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_privileges
     *
     * @mbg.generated
     */
    List<TablePrivileges> selectAll();
}