package com.alva.arbook.dao;

import com.alva.arbook.entity.TriggeredUpdateColumns;
import java.util.List;

public interface TriggeredUpdateColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table triggered_update_columns
     *
     * @mbg.generated
     */
    int insert(TriggeredUpdateColumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table triggered_update_columns
     *
     * @mbg.generated
     */
    List<TriggeredUpdateColumns> selectAll();
}