package com.alva.arbook.dao;

import com.alva.arbook.entity.UdtPrivileges;
import java.util.List;

public interface UdtPrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table udt_privileges
     *
     * @mbg.generated
     */
    int insert(UdtPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table udt_privileges
     *
     * @mbg.generated
     */
    List<UdtPrivileges> selectAll();
}