package com.alva.arbook.dao;

import com.alva.arbook.entity.UserMappingOptions;
import java.util.List;

public interface UserMappingOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mapping_options
     *
     * @mbg.generated
     */
    int insert(UserMappingOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mapping_options
     *
     * @mbg.generated
     */
    List<UserMappingOptions> selectAll();
}