package com.alva.arbook.dao;

import com.alva.arbook.entity.UserDefinedTypes;
import java.util.List;

public interface UserDefinedTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_types
     *
     * @mbg.generated
     */
    int insert(UserDefinedTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_types
     *
     * @mbg.generated
     */
    List<UserDefinedTypes> selectAll();
}