package com.alva.arbook.dao;

import com.alva.arbook.entity.Views;
import java.util.List;

public interface ViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table views
     *
     * @mbg.generated
     */
    int insert(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table views
     *
     * @mbg.generated
     */
    List<Views> selectAll();
}