package com.alva.arbook.dao;

import com.alva.arbook.entity.ViewRoutineUsage;
import java.util.List;

public interface ViewRoutineUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_routine_usage
     *
     * @mbg.generated
     */
    int insert(ViewRoutineUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_routine_usage
     *
     * @mbg.generated
     */
    List<ViewRoutineUsage> selectAll();
}