package com.alva.arbook.entity;

import java.io.Serializable;

public class CheckConstraints implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    private Object constraintCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_constraints.constraint_schema
     *
     * @mbg.generated
     */
    private Object constraintSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_constraints.constraint_name
     *
     * @mbg.generated
     */
    private Object constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_constraints.check_clause
     *
     * @mbg.generated
     */
    private Object checkClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table check_constraints
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_constraints.constraint_catalog
     *
     * @return the value of check_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    public Object getConstraintCatalog() {
        return constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_constraints.constraint_catalog
     *
     * @param constraintCatalog the value for check_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    public void setConstraintCatalog(Object constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_constraints.constraint_schema
     *
     * @return the value of check_constraints.constraint_schema
     *
     * @mbg.generated
     */
    public Object getConstraintSchema() {
        return constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_constraints.constraint_schema
     *
     * @param constraintSchema the value for check_constraints.constraint_schema
     *
     * @mbg.generated
     */
    public void setConstraintSchema(Object constraintSchema) {
        this.constraintSchema = constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_constraints.constraint_name
     *
     * @return the value of check_constraints.constraint_name
     *
     * @mbg.generated
     */
    public Object getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_constraints.constraint_name
     *
     * @param constraintName the value for check_constraints.constraint_name
     *
     * @mbg.generated
     */
    public void setConstraintName(Object constraintName) {
        this.constraintName = constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_constraints.check_clause
     *
     * @return the value of check_constraints.check_clause
     *
     * @mbg.generated
     */
    public Object getCheckClause() {
        return checkClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_constraints.check_clause
     *
     * @param checkClause the value for check_constraints.check_clause
     *
     * @mbg.generated
     */
    public void setCheckClause(Object checkClause) {
        this.checkClause = checkClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_constraints
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", constraintCatalog=").append(constraintCatalog);
        sb.append(", constraintSchema=").append(constraintSchema);
        sb.append(", constraintName=").append(constraintName);
        sb.append(", checkClause=").append(checkClause);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}