package com.alva.arbook.entity;

import java.io.Serializable;

public class Collations implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collations.collation_catalog
     *
     * @mbg.generated
     */
    private Object collationCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collations.collation_schema
     *
     * @mbg.generated
     */
    private Object collationSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collations.collation_name
     *
     * @mbg.generated
     */
    private Object collationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collations.pad_attribute
     *
     * @mbg.generated
     */
    private Object padAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collations
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collations.collation_catalog
     *
     * @return the value of collations.collation_catalog
     *
     * @mbg.generated
     */
    public Object getCollationCatalog() {
        return collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collations.collation_catalog
     *
     * @param collationCatalog the value for collations.collation_catalog
     *
     * @mbg.generated
     */
    public void setCollationCatalog(Object collationCatalog) {
        this.collationCatalog = collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collations.collation_schema
     *
     * @return the value of collations.collation_schema
     *
     * @mbg.generated
     */
    public Object getCollationSchema() {
        return collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collations.collation_schema
     *
     * @param collationSchema the value for collations.collation_schema
     *
     * @mbg.generated
     */
    public void setCollationSchema(Object collationSchema) {
        this.collationSchema = collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collations.collation_name
     *
     * @return the value of collations.collation_name
     *
     * @mbg.generated
     */
    public Object getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collations.collation_name
     *
     * @param collationName the value for collations.collation_name
     *
     * @mbg.generated
     */
    public void setCollationName(Object collationName) {
        this.collationName = collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collations.pad_attribute
     *
     * @return the value of collations.pad_attribute
     *
     * @mbg.generated
     */
    public Object getPadAttribute() {
        return padAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collations.pad_attribute
     *
     * @param padAttribute the value for collations.pad_attribute
     *
     * @mbg.generated
     */
    public void setPadAttribute(Object padAttribute) {
        this.padAttribute = padAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collations
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collationCatalog=").append(collationCatalog);
        sb.append(", collationSchema=").append(collationSchema);
        sb.append(", collationName=").append(collationName);
        sb.append(", padAttribute=").append(padAttribute);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}