package com.alva.arbook.entity;

import java.io.Serializable;

public class DomainUdtUsage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.udt_catalog
     *
     * @mbg.generated
     */
    private Object udtCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.udt_schema
     *
     * @mbg.generated
     */
    private Object udtSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.udt_name
     *
     * @mbg.generated
     */
    private Object udtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.domain_catalog
     *
     * @mbg.generated
     */
    private Object domainCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.domain_schema
     *
     * @mbg.generated
     */
    private Object domainSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_udt_usage.domain_name
     *
     * @mbg.generated
     */
    private Object domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_udt_usage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.udt_catalog
     *
     * @return the value of domain_udt_usage.udt_catalog
     *
     * @mbg.generated
     */
    public Object getUdtCatalog() {
        return udtCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.udt_catalog
     *
     * @param udtCatalog the value for domain_udt_usage.udt_catalog
     *
     * @mbg.generated
     */
    public void setUdtCatalog(Object udtCatalog) {
        this.udtCatalog = udtCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.udt_schema
     *
     * @return the value of domain_udt_usage.udt_schema
     *
     * @mbg.generated
     */
    public Object getUdtSchema() {
        return udtSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.udt_schema
     *
     * @param udtSchema the value for domain_udt_usage.udt_schema
     *
     * @mbg.generated
     */
    public void setUdtSchema(Object udtSchema) {
        this.udtSchema = udtSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.udt_name
     *
     * @return the value of domain_udt_usage.udt_name
     *
     * @mbg.generated
     */
    public Object getUdtName() {
        return udtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.udt_name
     *
     * @param udtName the value for domain_udt_usage.udt_name
     *
     * @mbg.generated
     */
    public void setUdtName(Object udtName) {
        this.udtName = udtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.domain_catalog
     *
     * @return the value of domain_udt_usage.domain_catalog
     *
     * @mbg.generated
     */
    public Object getDomainCatalog() {
        return domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.domain_catalog
     *
     * @param domainCatalog the value for domain_udt_usage.domain_catalog
     *
     * @mbg.generated
     */
    public void setDomainCatalog(Object domainCatalog) {
        this.domainCatalog = domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.domain_schema
     *
     * @return the value of domain_udt_usage.domain_schema
     *
     * @mbg.generated
     */
    public Object getDomainSchema() {
        return domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.domain_schema
     *
     * @param domainSchema the value for domain_udt_usage.domain_schema
     *
     * @mbg.generated
     */
    public void setDomainSchema(Object domainSchema) {
        this.domainSchema = domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_udt_usage.domain_name
     *
     * @return the value of domain_udt_usage.domain_name
     *
     * @mbg.generated
     */
    public Object getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_udt_usage.domain_name
     *
     * @param domainName the value for domain_udt_usage.domain_name
     *
     * @mbg.generated
     */
    public void setDomainName(Object domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_udt_usage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", udtCatalog=").append(udtCatalog);
        sb.append(", udtSchema=").append(udtSchema);
        sb.append(", udtName=").append(udtName);
        sb.append(", domainCatalog=").append(domainCatalog);
        sb.append(", domainSchema=").append(domainSchema);
        sb.append(", domainName=").append(domainName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}