package com.alva.arbook.entity;

import java.io.Serializable;

public class DomainConstraints implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    private Object constraintCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.constraint_schema
     *
     * @mbg.generated
     */
    private Object constraintSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.constraint_name
     *
     * @mbg.generated
     */
    private Object constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.domain_catalog
     *
     * @mbg.generated
     */
    private Object domainCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.domain_schema
     *
     * @mbg.generated
     */
    private Object domainSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.domain_name
     *
     * @mbg.generated
     */
    private Object domainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.is_deferrable
     *
     * @mbg.generated
     */
    private Object isDeferrable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_constraints.initially_deferred
     *
     * @mbg.generated
     */
    private Object initiallyDeferred;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table domain_constraints
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.constraint_catalog
     *
     * @return the value of domain_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    public Object getConstraintCatalog() {
        return constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.constraint_catalog
     *
     * @param constraintCatalog the value for domain_constraints.constraint_catalog
     *
     * @mbg.generated
     */
    public void setConstraintCatalog(Object constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.constraint_schema
     *
     * @return the value of domain_constraints.constraint_schema
     *
     * @mbg.generated
     */
    public Object getConstraintSchema() {
        return constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.constraint_schema
     *
     * @param constraintSchema the value for domain_constraints.constraint_schema
     *
     * @mbg.generated
     */
    public void setConstraintSchema(Object constraintSchema) {
        this.constraintSchema = constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.constraint_name
     *
     * @return the value of domain_constraints.constraint_name
     *
     * @mbg.generated
     */
    public Object getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.constraint_name
     *
     * @param constraintName the value for domain_constraints.constraint_name
     *
     * @mbg.generated
     */
    public void setConstraintName(Object constraintName) {
        this.constraintName = constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.domain_catalog
     *
     * @return the value of domain_constraints.domain_catalog
     *
     * @mbg.generated
     */
    public Object getDomainCatalog() {
        return domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.domain_catalog
     *
     * @param domainCatalog the value for domain_constraints.domain_catalog
     *
     * @mbg.generated
     */
    public void setDomainCatalog(Object domainCatalog) {
        this.domainCatalog = domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.domain_schema
     *
     * @return the value of domain_constraints.domain_schema
     *
     * @mbg.generated
     */
    public Object getDomainSchema() {
        return domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.domain_schema
     *
     * @param domainSchema the value for domain_constraints.domain_schema
     *
     * @mbg.generated
     */
    public void setDomainSchema(Object domainSchema) {
        this.domainSchema = domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.domain_name
     *
     * @return the value of domain_constraints.domain_name
     *
     * @mbg.generated
     */
    public Object getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.domain_name
     *
     * @param domainName the value for domain_constraints.domain_name
     *
     * @mbg.generated
     */
    public void setDomainName(Object domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.is_deferrable
     *
     * @return the value of domain_constraints.is_deferrable
     *
     * @mbg.generated
     */
    public Object getIsDeferrable() {
        return isDeferrable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.is_deferrable
     *
     * @param isDeferrable the value for domain_constraints.is_deferrable
     *
     * @mbg.generated
     */
    public void setIsDeferrable(Object isDeferrable) {
        this.isDeferrable = isDeferrable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_constraints.initially_deferred
     *
     * @return the value of domain_constraints.initially_deferred
     *
     * @mbg.generated
     */
    public Object getInitiallyDeferred() {
        return initiallyDeferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_constraints.initially_deferred
     *
     * @param initiallyDeferred the value for domain_constraints.initially_deferred
     *
     * @mbg.generated
     */
    public void setInitiallyDeferred(Object initiallyDeferred) {
        this.initiallyDeferred = initiallyDeferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_constraints
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", constraintCatalog=").append(constraintCatalog);
        sb.append(", constraintSchema=").append(constraintSchema);
        sb.append(", constraintName=").append(constraintName);
        sb.append(", domainCatalog=").append(domainCatalog);
        sb.append(", domainSchema=").append(domainSchema);
        sb.append(", domainName=").append(domainName);
        sb.append(", isDeferrable=").append(isDeferrable);
        sb.append(", initiallyDeferred=").append(initiallyDeferred);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}