package com.alva.arbook.entity;

import java.io.Serializable;

public class ForeignServerOptions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreign_server_options.foreign_server_catalog
     *
     * @mbg.generated
     */
    private Object foreignServerCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreign_server_options.foreign_server_name
     *
     * @mbg.generated
     */
    private Object foreignServerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreign_server_options.option_name
     *
     * @mbg.generated
     */
    private Object optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreign_server_options.option_value
     *
     * @mbg.generated
     */
    private Object optionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foreign_server_options
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreign_server_options.foreign_server_catalog
     *
     * @return the value of foreign_server_options.foreign_server_catalog
     *
     * @mbg.generated
     */
    public Object getForeignServerCatalog() {
        return foreignServerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreign_server_options.foreign_server_catalog
     *
     * @param foreignServerCatalog the value for foreign_server_options.foreign_server_catalog
     *
     * @mbg.generated
     */
    public void setForeignServerCatalog(Object foreignServerCatalog) {
        this.foreignServerCatalog = foreignServerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreign_server_options.foreign_server_name
     *
     * @return the value of foreign_server_options.foreign_server_name
     *
     * @mbg.generated
     */
    public Object getForeignServerName() {
        return foreignServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreign_server_options.foreign_server_name
     *
     * @param foreignServerName the value for foreign_server_options.foreign_server_name
     *
     * @mbg.generated
     */
    public void setForeignServerName(Object foreignServerName) {
        this.foreignServerName = foreignServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreign_server_options.option_name
     *
     * @return the value of foreign_server_options.option_name
     *
     * @mbg.generated
     */
    public Object getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreign_server_options.option_name
     *
     * @param optionName the value for foreign_server_options.option_name
     *
     * @mbg.generated
     */
    public void setOptionName(Object optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreign_server_options.option_value
     *
     * @return the value of foreign_server_options.option_value
     *
     * @mbg.generated
     */
    public Object getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreign_server_options.option_value
     *
     * @param optionValue the value for foreign_server_options.option_value
     *
     * @mbg.generated
     */
    public void setOptionValue(Object optionValue) {
        this.optionValue = optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_server_options
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", foreignServerCatalog=").append(foreignServerCatalog);
        sb.append(", foreignServerName=").append(foreignServerName);
        sb.append(", optionName=").append(optionName);
        sb.append(", optionValue=").append(optionValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}