package com.alva.arbook.entity;

import java.io.Serializable;

public class KeyColumnUsage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.constraint_catalog
     *
     * @mbg.generated
     */
    private Object constraintCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.constraint_schema
     *
     * @mbg.generated
     */
    private Object constraintSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.constraint_name
     *
     * @mbg.generated
     */
    private Object constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.table_catalog
     *
     * @mbg.generated
     */
    private Object tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.table_schema
     *
     * @mbg.generated
     */
    private Object tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.table_name
     *
     * @mbg.generated
     */
    private Object tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.column_name
     *
     * @mbg.generated
     */
    private Object columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.ordinal_position
     *
     * @mbg.generated
     */
    private Object ordinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_column_usage.position_in_unique_constraint
     *
     * @mbg.generated
     */
    private Object positionInUniqueConstraint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table key_column_usage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.constraint_catalog
     *
     * @return the value of key_column_usage.constraint_catalog
     *
     * @mbg.generated
     */
    public Object getConstraintCatalog() {
        return constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.constraint_catalog
     *
     * @param constraintCatalog the value for key_column_usage.constraint_catalog
     *
     * @mbg.generated
     */
    public void setConstraintCatalog(Object constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.constraint_schema
     *
     * @return the value of key_column_usage.constraint_schema
     *
     * @mbg.generated
     */
    public Object getConstraintSchema() {
        return constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.constraint_schema
     *
     * @param constraintSchema the value for key_column_usage.constraint_schema
     *
     * @mbg.generated
     */
    public void setConstraintSchema(Object constraintSchema) {
        this.constraintSchema = constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.constraint_name
     *
     * @return the value of key_column_usage.constraint_name
     *
     * @mbg.generated
     */
    public Object getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.constraint_name
     *
     * @param constraintName the value for key_column_usage.constraint_name
     *
     * @mbg.generated
     */
    public void setConstraintName(Object constraintName) {
        this.constraintName = constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.table_catalog
     *
     * @return the value of key_column_usage.table_catalog
     *
     * @mbg.generated
     */
    public Object getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.table_catalog
     *
     * @param tableCatalog the value for key_column_usage.table_catalog
     *
     * @mbg.generated
     */
    public void setTableCatalog(Object tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.table_schema
     *
     * @return the value of key_column_usage.table_schema
     *
     * @mbg.generated
     */
    public Object getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.table_schema
     *
     * @param tableSchema the value for key_column_usage.table_schema
     *
     * @mbg.generated
     */
    public void setTableSchema(Object tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.table_name
     *
     * @return the value of key_column_usage.table_name
     *
     * @mbg.generated
     */
    public Object getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.table_name
     *
     * @param tableName the value for key_column_usage.table_name
     *
     * @mbg.generated
     */
    public void setTableName(Object tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.column_name
     *
     * @return the value of key_column_usage.column_name
     *
     * @mbg.generated
     */
    public Object getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.column_name
     *
     * @param columnName the value for key_column_usage.column_name
     *
     * @mbg.generated
     */
    public void setColumnName(Object columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.ordinal_position
     *
     * @return the value of key_column_usage.ordinal_position
     *
     * @mbg.generated
     */
    public Object getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.ordinal_position
     *
     * @param ordinalPosition the value for key_column_usage.ordinal_position
     *
     * @mbg.generated
     */
    public void setOrdinalPosition(Object ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_column_usage.position_in_unique_constraint
     *
     * @return the value of key_column_usage.position_in_unique_constraint
     *
     * @mbg.generated
     */
    public Object getPositionInUniqueConstraint() {
        return positionInUniqueConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_column_usage.position_in_unique_constraint
     *
     * @param positionInUniqueConstraint the value for key_column_usage.position_in_unique_constraint
     *
     * @mbg.generated
     */
    public void setPositionInUniqueConstraint(Object positionInUniqueConstraint) {
        this.positionInUniqueConstraint = positionInUniqueConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_column_usage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", constraintCatalog=").append(constraintCatalog);
        sb.append(", constraintSchema=").append(constraintSchema);
        sb.append(", constraintName=").append(constraintName);
        sb.append(", tableCatalog=").append(tableCatalog);
        sb.append(", tableSchema=").append(tableSchema);
        sb.append(", tableName=").append(tableName);
        sb.append(", columnName=").append(columnName);
        sb.append(", ordinalPosition=").append(ordinalPosition);
        sb.append(", positionInUniqueConstraint=").append(positionInUniqueConstraint);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}