package com.alva.arbook.entity;

import java.io.Serializable;

public class Parameters implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.specific_catalog
     *
     * @mbg.generated
     */
    private Object specificCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.specific_schema
     *
     * @mbg.generated
     */
    private Object specificSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.specific_name
     *
     * @mbg.generated
     */
    private Object specificName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.ordinal_position
     *
     * @mbg.generated
     */
    private Object ordinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.parameter_mode
     *
     * @mbg.generated
     */
    private Object parameterMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.is_result
     *
     * @mbg.generated
     */
    private Object isResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.as_locator
     *
     * @mbg.generated
     */
    private Object asLocator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.parameter_name
     *
     * @mbg.generated
     */
    private Object parameterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.data_type
     *
     * @mbg.generated
     */
    private Object dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.character_maximum_length
     *
     * @mbg.generated
     */
    private Object characterMaximumLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.character_octet_length
     *
     * @mbg.generated
     */
    private Object characterOctetLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.character_set_catalog
     *
     * @mbg.generated
     */
    private Object characterSetCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.character_set_schema
     *
     * @mbg.generated
     */
    private Object characterSetSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.character_set_name
     *
     * @mbg.generated
     */
    private Object characterSetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.collation_catalog
     *
     * @mbg.generated
     */
    private Object collationCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.collation_schema
     *
     * @mbg.generated
     */
    private Object collationSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.collation_name
     *
     * @mbg.generated
     */
    private Object collationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.numeric_precision
     *
     * @mbg.generated
     */
    private Object numericPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.numeric_precision_radix
     *
     * @mbg.generated
     */
    private Object numericPrecisionRadix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.numeric_scale
     *
     * @mbg.generated
     */
    private Object numericScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.datetime_precision
     *
     * @mbg.generated
     */
    private Object datetimePrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.interval_type
     *
     * @mbg.generated
     */
    private Object intervalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.interval_precision
     *
     * @mbg.generated
     */
    private Object intervalPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.udt_catalog
     *
     * @mbg.generated
     */
    private Object udtCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.udt_schema
     *
     * @mbg.generated
     */
    private Object udtSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.udt_name
     *
     * @mbg.generated
     */
    private Object udtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.scope_catalog
     *
     * @mbg.generated
     */
    private Object scopeCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.scope_schema
     *
     * @mbg.generated
     */
    private Object scopeSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.scope_name
     *
     * @mbg.generated
     */
    private Object scopeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.maximum_cardinality
     *
     * @mbg.generated
     */
    private Object maximumCardinality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.dtd_identifier
     *
     * @mbg.generated
     */
    private Object dtdIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.parameter_default
     *
     * @mbg.generated
     */
    private Object parameterDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parameters
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.specific_catalog
     *
     * @return the value of parameters.specific_catalog
     *
     * @mbg.generated
     */
    public Object getSpecificCatalog() {
        return specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.specific_catalog
     *
     * @param specificCatalog the value for parameters.specific_catalog
     *
     * @mbg.generated
     */
    public void setSpecificCatalog(Object specificCatalog) {
        this.specificCatalog = specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.specific_schema
     *
     * @return the value of parameters.specific_schema
     *
     * @mbg.generated
     */
    public Object getSpecificSchema() {
        return specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.specific_schema
     *
     * @param specificSchema the value for parameters.specific_schema
     *
     * @mbg.generated
     */
    public void setSpecificSchema(Object specificSchema) {
        this.specificSchema = specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.specific_name
     *
     * @return the value of parameters.specific_name
     *
     * @mbg.generated
     */
    public Object getSpecificName() {
        return specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.specific_name
     *
     * @param specificName the value for parameters.specific_name
     *
     * @mbg.generated
     */
    public void setSpecificName(Object specificName) {
        this.specificName = specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.ordinal_position
     *
     * @return the value of parameters.ordinal_position
     *
     * @mbg.generated
     */
    public Object getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.ordinal_position
     *
     * @param ordinalPosition the value for parameters.ordinal_position
     *
     * @mbg.generated
     */
    public void setOrdinalPosition(Object ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.parameter_mode
     *
     * @return the value of parameters.parameter_mode
     *
     * @mbg.generated
     */
    public Object getParameterMode() {
        return parameterMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.parameter_mode
     *
     * @param parameterMode the value for parameters.parameter_mode
     *
     * @mbg.generated
     */
    public void setParameterMode(Object parameterMode) {
        this.parameterMode = parameterMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.is_result
     *
     * @return the value of parameters.is_result
     *
     * @mbg.generated
     */
    public Object getIsResult() {
        return isResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.is_result
     *
     * @param isResult the value for parameters.is_result
     *
     * @mbg.generated
     */
    public void setIsResult(Object isResult) {
        this.isResult = isResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.as_locator
     *
     * @return the value of parameters.as_locator
     *
     * @mbg.generated
     */
    public Object getAsLocator() {
        return asLocator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.as_locator
     *
     * @param asLocator the value for parameters.as_locator
     *
     * @mbg.generated
     */
    public void setAsLocator(Object asLocator) {
        this.asLocator = asLocator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.parameter_name
     *
     * @return the value of parameters.parameter_name
     *
     * @mbg.generated
     */
    public Object getParameterName() {
        return parameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.parameter_name
     *
     * @param parameterName the value for parameters.parameter_name
     *
     * @mbg.generated
     */
    public void setParameterName(Object parameterName) {
        this.parameterName = parameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.data_type
     *
     * @return the value of parameters.data_type
     *
     * @mbg.generated
     */
    public Object getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.data_type
     *
     * @param dataType the value for parameters.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Object dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.character_maximum_length
     *
     * @return the value of parameters.character_maximum_length
     *
     * @mbg.generated
     */
    public Object getCharacterMaximumLength() {
        return characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.character_maximum_length
     *
     * @param characterMaximumLength the value for parameters.character_maximum_length
     *
     * @mbg.generated
     */
    public void setCharacterMaximumLength(Object characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.character_octet_length
     *
     * @return the value of parameters.character_octet_length
     *
     * @mbg.generated
     */
    public Object getCharacterOctetLength() {
        return characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.character_octet_length
     *
     * @param characterOctetLength the value for parameters.character_octet_length
     *
     * @mbg.generated
     */
    public void setCharacterOctetLength(Object characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.character_set_catalog
     *
     * @return the value of parameters.character_set_catalog
     *
     * @mbg.generated
     */
    public Object getCharacterSetCatalog() {
        return characterSetCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.character_set_catalog
     *
     * @param characterSetCatalog the value for parameters.character_set_catalog
     *
     * @mbg.generated
     */
    public void setCharacterSetCatalog(Object characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.character_set_schema
     *
     * @return the value of parameters.character_set_schema
     *
     * @mbg.generated
     */
    public Object getCharacterSetSchema() {
        return characterSetSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.character_set_schema
     *
     * @param characterSetSchema the value for parameters.character_set_schema
     *
     * @mbg.generated
     */
    public void setCharacterSetSchema(Object characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.character_set_name
     *
     * @return the value of parameters.character_set_name
     *
     * @mbg.generated
     */
    public Object getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.character_set_name
     *
     * @param characterSetName the value for parameters.character_set_name
     *
     * @mbg.generated
     */
    public void setCharacterSetName(Object characterSetName) {
        this.characterSetName = characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.collation_catalog
     *
     * @return the value of parameters.collation_catalog
     *
     * @mbg.generated
     */
    public Object getCollationCatalog() {
        return collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.collation_catalog
     *
     * @param collationCatalog the value for parameters.collation_catalog
     *
     * @mbg.generated
     */
    public void setCollationCatalog(Object collationCatalog) {
        this.collationCatalog = collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.collation_schema
     *
     * @return the value of parameters.collation_schema
     *
     * @mbg.generated
     */
    public Object getCollationSchema() {
        return collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.collation_schema
     *
     * @param collationSchema the value for parameters.collation_schema
     *
     * @mbg.generated
     */
    public void setCollationSchema(Object collationSchema) {
        this.collationSchema = collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.collation_name
     *
     * @return the value of parameters.collation_name
     *
     * @mbg.generated
     */
    public Object getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.collation_name
     *
     * @param collationName the value for parameters.collation_name
     *
     * @mbg.generated
     */
    public void setCollationName(Object collationName) {
        this.collationName = collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.numeric_precision
     *
     * @return the value of parameters.numeric_precision
     *
     * @mbg.generated
     */
    public Object getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.numeric_precision
     *
     * @param numericPrecision the value for parameters.numeric_precision
     *
     * @mbg.generated
     */
    public void setNumericPrecision(Object numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.numeric_precision_radix
     *
     * @return the value of parameters.numeric_precision_radix
     *
     * @mbg.generated
     */
    public Object getNumericPrecisionRadix() {
        return numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.numeric_precision_radix
     *
     * @param numericPrecisionRadix the value for parameters.numeric_precision_radix
     *
     * @mbg.generated
     */
    public void setNumericPrecisionRadix(Object numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.numeric_scale
     *
     * @return the value of parameters.numeric_scale
     *
     * @mbg.generated
     */
    public Object getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.numeric_scale
     *
     * @param numericScale the value for parameters.numeric_scale
     *
     * @mbg.generated
     */
    public void setNumericScale(Object numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.datetime_precision
     *
     * @return the value of parameters.datetime_precision
     *
     * @mbg.generated
     */
    public Object getDatetimePrecision() {
        return datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.datetime_precision
     *
     * @param datetimePrecision the value for parameters.datetime_precision
     *
     * @mbg.generated
     */
    public void setDatetimePrecision(Object datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.interval_type
     *
     * @return the value of parameters.interval_type
     *
     * @mbg.generated
     */
    public Object getIntervalType() {
        return intervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.interval_type
     *
     * @param intervalType the value for parameters.interval_type
     *
     * @mbg.generated
     */
    public void setIntervalType(Object intervalType) {
        this.intervalType = intervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.interval_precision
     *
     * @return the value of parameters.interval_precision
     *
     * @mbg.generated
     */
    public Object getIntervalPrecision() {
        return intervalPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.interval_precision
     *
     * @param intervalPrecision the value for parameters.interval_precision
     *
     * @mbg.generated
     */
    public void setIntervalPrecision(Object intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.udt_catalog
     *
     * @return the value of parameters.udt_catalog
     *
     * @mbg.generated
     */
    public Object getUdtCatalog() {
        return udtCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.udt_catalog
     *
     * @param udtCatalog the value for parameters.udt_catalog
     *
     * @mbg.generated
     */
    public void setUdtCatalog(Object udtCatalog) {
        this.udtCatalog = udtCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.udt_schema
     *
     * @return the value of parameters.udt_schema
     *
     * @mbg.generated
     */
    public Object getUdtSchema() {
        return udtSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.udt_schema
     *
     * @param udtSchema the value for parameters.udt_schema
     *
     * @mbg.generated
     */
    public void setUdtSchema(Object udtSchema) {
        this.udtSchema = udtSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.udt_name
     *
     * @return the value of parameters.udt_name
     *
     * @mbg.generated
     */
    public Object getUdtName() {
        return udtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.udt_name
     *
     * @param udtName the value for parameters.udt_name
     *
     * @mbg.generated
     */
    public void setUdtName(Object udtName) {
        this.udtName = udtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.scope_catalog
     *
     * @return the value of parameters.scope_catalog
     *
     * @mbg.generated
     */
    public Object getScopeCatalog() {
        return scopeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.scope_catalog
     *
     * @param scopeCatalog the value for parameters.scope_catalog
     *
     * @mbg.generated
     */
    public void setScopeCatalog(Object scopeCatalog) {
        this.scopeCatalog = scopeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.scope_schema
     *
     * @return the value of parameters.scope_schema
     *
     * @mbg.generated
     */
    public Object getScopeSchema() {
        return scopeSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.scope_schema
     *
     * @param scopeSchema the value for parameters.scope_schema
     *
     * @mbg.generated
     */
    public void setScopeSchema(Object scopeSchema) {
        this.scopeSchema = scopeSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.scope_name
     *
     * @return the value of parameters.scope_name
     *
     * @mbg.generated
     */
    public Object getScopeName() {
        return scopeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.scope_name
     *
     * @param scopeName the value for parameters.scope_name
     *
     * @mbg.generated
     */
    public void setScopeName(Object scopeName) {
        this.scopeName = scopeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.maximum_cardinality
     *
     * @return the value of parameters.maximum_cardinality
     *
     * @mbg.generated
     */
    public Object getMaximumCardinality() {
        return maximumCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.maximum_cardinality
     *
     * @param maximumCardinality the value for parameters.maximum_cardinality
     *
     * @mbg.generated
     */
    public void setMaximumCardinality(Object maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.dtd_identifier
     *
     * @return the value of parameters.dtd_identifier
     *
     * @mbg.generated
     */
    public Object getDtdIdentifier() {
        return dtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.dtd_identifier
     *
     * @param dtdIdentifier the value for parameters.dtd_identifier
     *
     * @mbg.generated
     */
    public void setDtdIdentifier(Object dtdIdentifier) {
        this.dtdIdentifier = dtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.parameter_default
     *
     * @return the value of parameters.parameter_default
     *
     * @mbg.generated
     */
    public Object getParameterDefault() {
        return parameterDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.parameter_default
     *
     * @param parameterDefault the value for parameters.parameter_default
     *
     * @mbg.generated
     */
    public void setParameterDefault(Object parameterDefault) {
        this.parameterDefault = parameterDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", specificCatalog=").append(specificCatalog);
        sb.append(", specificSchema=").append(specificSchema);
        sb.append(", specificName=").append(specificName);
        sb.append(", ordinalPosition=").append(ordinalPosition);
        sb.append(", parameterMode=").append(parameterMode);
        sb.append(", isResult=").append(isResult);
        sb.append(", asLocator=").append(asLocator);
        sb.append(", parameterName=").append(parameterName);
        sb.append(", dataType=").append(dataType);
        sb.append(", characterMaximumLength=").append(characterMaximumLength);
        sb.append(", characterOctetLength=").append(characterOctetLength);
        sb.append(", characterSetCatalog=").append(characterSetCatalog);
        sb.append(", characterSetSchema=").append(characterSetSchema);
        sb.append(", characterSetName=").append(characterSetName);
        sb.append(", collationCatalog=").append(collationCatalog);
        sb.append(", collationSchema=").append(collationSchema);
        sb.append(", collationName=").append(collationName);
        sb.append(", numericPrecision=").append(numericPrecision);
        sb.append(", numericPrecisionRadix=").append(numericPrecisionRadix);
        sb.append(", numericScale=").append(numericScale);
        sb.append(", datetimePrecision=").append(datetimePrecision);
        sb.append(", intervalType=").append(intervalType);
        sb.append(", intervalPrecision=").append(intervalPrecision);
        sb.append(", udtCatalog=").append(udtCatalog);
        sb.append(", udtSchema=").append(udtSchema);
        sb.append(", udtName=").append(udtName);
        sb.append(", scopeCatalog=").append(scopeCatalog);
        sb.append(", scopeSchema=").append(scopeSchema);
        sb.append(", scopeName=").append(scopeName);
        sb.append(", maximumCardinality=").append(maximumCardinality);
        sb.append(", dtdIdentifier=").append(dtdIdentifier);
        sb.append(", parameterDefault=").append(parameterDefault);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}