package com.alva.arbook.entity;

import java.io.Serializable;

public class PgAm implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_am.amname
     *
     * @mbg.generated
     */
    private String amname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_am.amhandler
     *
     * @mbg.generated
     */
    private Object amhandler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_am.amtype
     *
     * @mbg.generated
     */
    private String amtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_am
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_am.amname
     *
     * @return the value of pg_am.amname
     *
     * @mbg.generated
     */
    public String getAmname() {
        return amname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_am.amname
     *
     * @param amname the value for pg_am.amname
     *
     * @mbg.generated
     */
    public void setAmname(String amname) {
        this.amname = amname == null ? null : amname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_am.amhandler
     *
     * @return the value of pg_am.amhandler
     *
     * @mbg.generated
     */
    public Object getAmhandler() {
        return amhandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_am.amhandler
     *
     * @param amhandler the value for pg_am.amhandler
     *
     * @mbg.generated
     */
    public void setAmhandler(Object amhandler) {
        this.amhandler = amhandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_am.amtype
     *
     * @return the value of pg_am.amtype
     *
     * @mbg.generated
     */
    public String getAmtype() {
        return amtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_am.amtype
     *
     * @param amtype the value for pg_am.amtype
     *
     * @mbg.generated
     */
    public void setAmtype(String amtype) {
        this.amtype = amtype == null ? null : amtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_am
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", amname=").append(amname);
        sb.append(", amhandler=").append(amhandler);
        sb.append(", amtype=").append(amtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}