package com.alva.arbook.entity;

import java.io.Serializable;

public class PgAttrdef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_attrdef.adrelid
     *
     * @mbg.generated
     */
    private Long adrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_attrdef.adnum
     *
     * @mbg.generated
     */
    private Short adnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_attrdef.adbin
     *
     * @mbg.generated
     */
    private Object adbin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_attrdef.adsrc
     *
     * @mbg.generated
     */
    private String adsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_attrdef
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_attrdef.adrelid
     *
     * @return the value of pg_attrdef.adrelid
     *
     * @mbg.generated
     */
    public Long getAdrelid() {
        return adrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_attrdef.adrelid
     *
     * @param adrelid the value for pg_attrdef.adrelid
     *
     * @mbg.generated
     */
    public void setAdrelid(Long adrelid) {
        this.adrelid = adrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_attrdef.adnum
     *
     * @return the value of pg_attrdef.adnum
     *
     * @mbg.generated
     */
    public Short getAdnum() {
        return adnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_attrdef.adnum
     *
     * @param adnum the value for pg_attrdef.adnum
     *
     * @mbg.generated
     */
    public void setAdnum(Short adnum) {
        this.adnum = adnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_attrdef.adbin
     *
     * @return the value of pg_attrdef.adbin
     *
     * @mbg.generated
     */
    public Object getAdbin() {
        return adbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_attrdef.adbin
     *
     * @param adbin the value for pg_attrdef.adbin
     *
     * @mbg.generated
     */
    public void setAdbin(Object adbin) {
        this.adbin = adbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_attrdef.adsrc
     *
     * @return the value of pg_attrdef.adsrc
     *
     * @mbg.generated
     */
    public String getAdsrc() {
        return adsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_attrdef.adsrc
     *
     * @param adsrc the value for pg_attrdef.adsrc
     *
     * @mbg.generated
     */
    public void setAdsrc(String adsrc) {
        this.adsrc = adsrc == null ? null : adsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_attrdef
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adrelid=").append(adrelid);
        sb.append(", adnum=").append(adnum);
        sb.append(", adbin=").append(adbin);
        sb.append(", adsrc=").append(adsrc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}