package com.alva.arbook.entity;

import java.io.Serializable;

public class PgConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_config.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_config.setting
     *
     * @mbg.generated
     */
    private String setting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_config.name
     *
     * @return the value of pg_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_config.name
     *
     * @param name the value for pg_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_config.setting
     *
     * @return the value of pg_config.setting
     *
     * @mbg.generated
     */
    public String getSetting() {
        return setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_config.setting
     *
     * @param setting the value for pg_config.setting
     *
     * @mbg.generated
     */
    public void setSetting(String setting) {
        this.setting = setting == null ? null : setting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", setting=").append(setting);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}