package com.alva.arbook.entity;

import java.io.Serializable;

public class PgDatabase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datname
     *
     * @mbg.generated
     */
    private String datname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datdba
     *
     * @mbg.generated
     */
    private Long datdba;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.encoding
     *
     * @mbg.generated
     */
    private Integer encoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datcollate
     *
     * @mbg.generated
     */
    private String datcollate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datctype
     *
     * @mbg.generated
     */
    private String datctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datistemplate
     *
     * @mbg.generated
     */
    private Boolean datistemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datallowconn
     *
     * @mbg.generated
     */
    private Boolean datallowconn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datconnlimit
     *
     * @mbg.generated
     */
    private Integer datconnlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datlastsysoid
     *
     * @mbg.generated
     */
    private Long datlastsysoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datfrozenxid
     *
     * @mbg.generated
     */
    private Object datfrozenxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datminmxid
     *
     * @mbg.generated
     */
    private Object datminmxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.dattablespace
     *
     * @mbg.generated
     */
    private Long dattablespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_database.datacl
     *
     * @mbg.generated
     */
    private Object datacl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_database
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datname
     *
     * @return the value of pg_database.datname
     *
     * @mbg.generated
     */
    public String getDatname() {
        return datname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datname
     *
     * @param datname the value for pg_database.datname
     *
     * @mbg.generated
     */
    public void setDatname(String datname) {
        this.datname = datname == null ? null : datname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datdba
     *
     * @return the value of pg_database.datdba
     *
     * @mbg.generated
     */
    public Long getDatdba() {
        return datdba;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datdba
     *
     * @param datdba the value for pg_database.datdba
     *
     * @mbg.generated
     */
    public void setDatdba(Long datdba) {
        this.datdba = datdba;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.encoding
     *
     * @return the value of pg_database.encoding
     *
     * @mbg.generated
     */
    public Integer getEncoding() {
        return encoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.encoding
     *
     * @param encoding the value for pg_database.encoding
     *
     * @mbg.generated
     */
    public void setEncoding(Integer encoding) {
        this.encoding = encoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datcollate
     *
     * @return the value of pg_database.datcollate
     *
     * @mbg.generated
     */
    public String getDatcollate() {
        return datcollate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datcollate
     *
     * @param datcollate the value for pg_database.datcollate
     *
     * @mbg.generated
     */
    public void setDatcollate(String datcollate) {
        this.datcollate = datcollate == null ? null : datcollate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datctype
     *
     * @return the value of pg_database.datctype
     *
     * @mbg.generated
     */
    public String getDatctype() {
        return datctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datctype
     *
     * @param datctype the value for pg_database.datctype
     *
     * @mbg.generated
     */
    public void setDatctype(String datctype) {
        this.datctype = datctype == null ? null : datctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datistemplate
     *
     * @return the value of pg_database.datistemplate
     *
     * @mbg.generated
     */
    public Boolean getDatistemplate() {
        return datistemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datistemplate
     *
     * @param datistemplate the value for pg_database.datistemplate
     *
     * @mbg.generated
     */
    public void setDatistemplate(Boolean datistemplate) {
        this.datistemplate = datistemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datallowconn
     *
     * @return the value of pg_database.datallowconn
     *
     * @mbg.generated
     */
    public Boolean getDatallowconn() {
        return datallowconn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datallowconn
     *
     * @param datallowconn the value for pg_database.datallowconn
     *
     * @mbg.generated
     */
    public void setDatallowconn(Boolean datallowconn) {
        this.datallowconn = datallowconn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datconnlimit
     *
     * @return the value of pg_database.datconnlimit
     *
     * @mbg.generated
     */
    public Integer getDatconnlimit() {
        return datconnlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datconnlimit
     *
     * @param datconnlimit the value for pg_database.datconnlimit
     *
     * @mbg.generated
     */
    public void setDatconnlimit(Integer datconnlimit) {
        this.datconnlimit = datconnlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datlastsysoid
     *
     * @return the value of pg_database.datlastsysoid
     *
     * @mbg.generated
     */
    public Long getDatlastsysoid() {
        return datlastsysoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datlastsysoid
     *
     * @param datlastsysoid the value for pg_database.datlastsysoid
     *
     * @mbg.generated
     */
    public void setDatlastsysoid(Long datlastsysoid) {
        this.datlastsysoid = datlastsysoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datfrozenxid
     *
     * @return the value of pg_database.datfrozenxid
     *
     * @mbg.generated
     */
    public Object getDatfrozenxid() {
        return datfrozenxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datfrozenxid
     *
     * @param datfrozenxid the value for pg_database.datfrozenxid
     *
     * @mbg.generated
     */
    public void setDatfrozenxid(Object datfrozenxid) {
        this.datfrozenxid = datfrozenxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datminmxid
     *
     * @return the value of pg_database.datminmxid
     *
     * @mbg.generated
     */
    public Object getDatminmxid() {
        return datminmxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datminmxid
     *
     * @param datminmxid the value for pg_database.datminmxid
     *
     * @mbg.generated
     */
    public void setDatminmxid(Object datminmxid) {
        this.datminmxid = datminmxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.dattablespace
     *
     * @return the value of pg_database.dattablespace
     *
     * @mbg.generated
     */
    public Long getDattablespace() {
        return dattablespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.dattablespace
     *
     * @param dattablespace the value for pg_database.dattablespace
     *
     * @mbg.generated
     */
    public void setDattablespace(Long dattablespace) {
        this.dattablespace = dattablespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_database.datacl
     *
     * @return the value of pg_database.datacl
     *
     * @mbg.generated
     */
    public Object getDatacl() {
        return datacl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_database.datacl
     *
     * @param datacl the value for pg_database.datacl
     *
     * @mbg.generated
     */
    public void setDatacl(Object datacl) {
        this.datacl = datacl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_database
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", datname=").append(datname);
        sb.append(", datdba=").append(datdba);
        sb.append(", encoding=").append(encoding);
        sb.append(", datcollate=").append(datcollate);
        sb.append(", datctype=").append(datctype);
        sb.append(", datistemplate=").append(datistemplate);
        sb.append(", datallowconn=").append(datallowconn);
        sb.append(", datconnlimit=").append(datconnlimit);
        sb.append(", datlastsysoid=").append(datlastsysoid);
        sb.append(", datfrozenxid=").append(datfrozenxid);
        sb.append(", datminmxid=").append(datminmxid);
        sb.append(", dattablespace=").append(dattablespace);
        sb.append(", datacl=").append(datacl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}