package com.alva.arbook.entity;

import java.io.Serializable;

public class PgEnum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_enum.enumtypid
     *
     * @mbg.generated
     */
    private Long enumtypid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_enum.enumsortorder
     *
     * @mbg.generated
     */
    private Float enumsortorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_enum.enumlabel
     *
     * @mbg.generated
     */
    private String enumlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_enum
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_enum.enumtypid
     *
     * @return the value of pg_enum.enumtypid
     *
     * @mbg.generated
     */
    public Long getEnumtypid() {
        return enumtypid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_enum.enumtypid
     *
     * @param enumtypid the value for pg_enum.enumtypid
     *
     * @mbg.generated
     */
    public void setEnumtypid(Long enumtypid) {
        this.enumtypid = enumtypid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_enum.enumsortorder
     *
     * @return the value of pg_enum.enumsortorder
     *
     * @mbg.generated
     */
    public Float getEnumsortorder() {
        return enumsortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_enum.enumsortorder
     *
     * @param enumsortorder the value for pg_enum.enumsortorder
     *
     * @mbg.generated
     */
    public void setEnumsortorder(Float enumsortorder) {
        this.enumsortorder = enumsortorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_enum.enumlabel
     *
     * @return the value of pg_enum.enumlabel
     *
     * @mbg.generated
     */
    public String getEnumlabel() {
        return enumlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_enum.enumlabel
     *
     * @param enumlabel the value for pg_enum.enumlabel
     *
     * @mbg.generated
     */
    public void setEnumlabel(String enumlabel) {
        this.enumlabel = enumlabel == null ? null : enumlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_enum
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", enumtypid=").append(enumtypid);
        sb.append(", enumsortorder=").append(enumsortorder);
        sb.append(", enumlabel=").append(enumlabel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}