package com.alva.arbook.entity;

import java.io.Serializable;

public class PgEventTrigger implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evtname
     *
     * @mbg.generated
     */
    private String evtname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evtevent
     *
     * @mbg.generated
     */
    private String evtevent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evtowner
     *
     * @mbg.generated
     */
    private Long evtowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evtfoid
     *
     * @mbg.generated
     */
    private Long evtfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evtenabled
     *
     * @mbg.generated
     */
    private String evtenabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_event_trigger.evttags
     *
     * @mbg.generated
     */
    private Object evttags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_event_trigger
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evtname
     *
     * @return the value of pg_event_trigger.evtname
     *
     * @mbg.generated
     */
    public String getEvtname() {
        return evtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evtname
     *
     * @param evtname the value for pg_event_trigger.evtname
     *
     * @mbg.generated
     */
    public void setEvtname(String evtname) {
        this.evtname = evtname == null ? null : evtname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evtevent
     *
     * @return the value of pg_event_trigger.evtevent
     *
     * @mbg.generated
     */
    public String getEvtevent() {
        return evtevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evtevent
     *
     * @param evtevent the value for pg_event_trigger.evtevent
     *
     * @mbg.generated
     */
    public void setEvtevent(String evtevent) {
        this.evtevent = evtevent == null ? null : evtevent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evtowner
     *
     * @return the value of pg_event_trigger.evtowner
     *
     * @mbg.generated
     */
    public Long getEvtowner() {
        return evtowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evtowner
     *
     * @param evtowner the value for pg_event_trigger.evtowner
     *
     * @mbg.generated
     */
    public void setEvtowner(Long evtowner) {
        this.evtowner = evtowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evtfoid
     *
     * @return the value of pg_event_trigger.evtfoid
     *
     * @mbg.generated
     */
    public Long getEvtfoid() {
        return evtfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evtfoid
     *
     * @param evtfoid the value for pg_event_trigger.evtfoid
     *
     * @mbg.generated
     */
    public void setEvtfoid(Long evtfoid) {
        this.evtfoid = evtfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evtenabled
     *
     * @return the value of pg_event_trigger.evtenabled
     *
     * @mbg.generated
     */
    public String getEvtenabled() {
        return evtenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evtenabled
     *
     * @param evtenabled the value for pg_event_trigger.evtenabled
     *
     * @mbg.generated
     */
    public void setEvtenabled(String evtenabled) {
        this.evtenabled = evtenabled == null ? null : evtenabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_event_trigger.evttags
     *
     * @return the value of pg_event_trigger.evttags
     *
     * @mbg.generated
     */
    public Object getEvttags() {
        return evttags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_event_trigger.evttags
     *
     * @param evttags the value for pg_event_trigger.evttags
     *
     * @mbg.generated
     */
    public void setEvttags(Object evttags) {
        this.evttags = evttags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_event_trigger
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", evtname=").append(evtname);
        sb.append(", evtevent=").append(evtevent);
        sb.append(", evtowner=").append(evtowner);
        sb.append(", evtfoid=").append(evtfoid);
        sb.append(", evtenabled=").append(evtenabled);
        sb.append(", evttags=").append(evttags);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}