package com.alva.arbook.entity;

import java.io.Serializable;

public class PgForeignTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_foreign_table.ftrelid
     *
     * @mbg.generated
     */
    private Long ftrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_foreign_table.ftserver
     *
     * @mbg.generated
     */
    private Long ftserver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_foreign_table.ftoptions
     *
     * @mbg.generated
     */
    private Object ftoptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_foreign_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_foreign_table.ftrelid
     *
     * @return the value of pg_foreign_table.ftrelid
     *
     * @mbg.generated
     */
    public Long getFtrelid() {
        return ftrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_foreign_table.ftrelid
     *
     * @param ftrelid the value for pg_foreign_table.ftrelid
     *
     * @mbg.generated
     */
    public void setFtrelid(Long ftrelid) {
        this.ftrelid = ftrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_foreign_table.ftserver
     *
     * @return the value of pg_foreign_table.ftserver
     *
     * @mbg.generated
     */
    public Long getFtserver() {
        return ftserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_foreign_table.ftserver
     *
     * @param ftserver the value for pg_foreign_table.ftserver
     *
     * @mbg.generated
     */
    public void setFtserver(Long ftserver) {
        this.ftserver = ftserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_foreign_table.ftoptions
     *
     * @return the value of pg_foreign_table.ftoptions
     *
     * @mbg.generated
     */
    public Object getFtoptions() {
        return ftoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_foreign_table.ftoptions
     *
     * @param ftoptions the value for pg_foreign_table.ftoptions
     *
     * @mbg.generated
     */
    public void setFtoptions(Object ftoptions) {
        this.ftoptions = ftoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_foreign_table
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ftrelid=").append(ftrelid);
        sb.append(", ftserver=").append(ftserver);
        sb.append(", ftoptions=").append(ftoptions);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}