package com.alva.arbook.entity;

import java.io.Serializable;

public class PgForeignTables implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.foreign_table_catalog
     *
     * @mbg.generated
     */
    private Object foreignTableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.foreign_table_schema
     *
     * @mbg.generated
     */
    private Object foreignTableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.foreign_table_name
     *
     * @mbg.generated
     */
    private Object foreignTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.ftoptions
     *
     * @mbg.generated
     */
    private Object ftoptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.foreign_server_catalog
     *
     * @mbg.generated
     */
    private Object foreignServerCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.foreign_server_name
     *
     * @mbg.generated
     */
    private Object foreignServerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _pg_foreign_tables.authorization_identifier
     *
     * @mbg.generated
     */
    private Object authorizationIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _pg_foreign_tables
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.foreign_table_catalog
     *
     * @return the value of _pg_foreign_tables.foreign_table_catalog
     *
     * @mbg.generated
     */
    public Object getForeignTableCatalog() {
        return foreignTableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.foreign_table_catalog
     *
     * @param foreignTableCatalog the value for _pg_foreign_tables.foreign_table_catalog
     *
     * @mbg.generated
     */
    public void setForeignTableCatalog(Object foreignTableCatalog) {
        this.foreignTableCatalog = foreignTableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.foreign_table_schema
     *
     * @return the value of _pg_foreign_tables.foreign_table_schema
     *
     * @mbg.generated
     */
    public Object getForeignTableSchema() {
        return foreignTableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.foreign_table_schema
     *
     * @param foreignTableSchema the value for _pg_foreign_tables.foreign_table_schema
     *
     * @mbg.generated
     */
    public void setForeignTableSchema(Object foreignTableSchema) {
        this.foreignTableSchema = foreignTableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.foreign_table_name
     *
     * @return the value of _pg_foreign_tables.foreign_table_name
     *
     * @mbg.generated
     */
    public Object getForeignTableName() {
        return foreignTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.foreign_table_name
     *
     * @param foreignTableName the value for _pg_foreign_tables.foreign_table_name
     *
     * @mbg.generated
     */
    public void setForeignTableName(Object foreignTableName) {
        this.foreignTableName = foreignTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.ftoptions
     *
     * @return the value of _pg_foreign_tables.ftoptions
     *
     * @mbg.generated
     */
    public Object getFtoptions() {
        return ftoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.ftoptions
     *
     * @param ftoptions the value for _pg_foreign_tables.ftoptions
     *
     * @mbg.generated
     */
    public void setFtoptions(Object ftoptions) {
        this.ftoptions = ftoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.foreign_server_catalog
     *
     * @return the value of _pg_foreign_tables.foreign_server_catalog
     *
     * @mbg.generated
     */
    public Object getForeignServerCatalog() {
        return foreignServerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.foreign_server_catalog
     *
     * @param foreignServerCatalog the value for _pg_foreign_tables.foreign_server_catalog
     *
     * @mbg.generated
     */
    public void setForeignServerCatalog(Object foreignServerCatalog) {
        this.foreignServerCatalog = foreignServerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.foreign_server_name
     *
     * @return the value of _pg_foreign_tables.foreign_server_name
     *
     * @mbg.generated
     */
    public Object getForeignServerName() {
        return foreignServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.foreign_server_name
     *
     * @param foreignServerName the value for _pg_foreign_tables.foreign_server_name
     *
     * @mbg.generated
     */
    public void setForeignServerName(Object foreignServerName) {
        this.foreignServerName = foreignServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _pg_foreign_tables.authorization_identifier
     *
     * @return the value of _pg_foreign_tables.authorization_identifier
     *
     * @mbg.generated
     */
    public Object getAuthorizationIdentifier() {
        return authorizationIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _pg_foreign_tables.authorization_identifier
     *
     * @param authorizationIdentifier the value for _pg_foreign_tables.authorization_identifier
     *
     * @mbg.generated
     */
    public void setAuthorizationIdentifier(Object authorizationIdentifier) {
        this.authorizationIdentifier = authorizationIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _pg_foreign_tables
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", foreignTableCatalog=").append(foreignTableCatalog);
        sb.append(", foreignTableSchema=").append(foreignTableSchema);
        sb.append(", foreignTableName=").append(foreignTableName);
        sb.append(", ftoptions=").append(ftoptions);
        sb.append(", foreignServerCatalog=").append(foreignServerCatalog);
        sb.append(", foreignServerName=").append(foreignServerName);
        sb.append(", authorizationIdentifier=").append(authorizationIdentifier);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}