package com.alva.arbook.entity;

import java.io.Serializable;

public class PgIndex implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indexrelid
     *
     * @mbg.generated
     */
    private Long indexrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indrelid
     *
     * @mbg.generated
     */
    private Long indrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indnatts
     *
     * @mbg.generated
     */
    private Short indnatts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisunique
     *
     * @mbg.generated
     */
    private Boolean indisunique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisprimary
     *
     * @mbg.generated
     */
    private Boolean indisprimary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisexclusion
     *
     * @mbg.generated
     */
    private Boolean indisexclusion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indimmediate
     *
     * @mbg.generated
     */
    private Boolean indimmediate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisclustered
     *
     * @mbg.generated
     */
    private Boolean indisclustered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisvalid
     *
     * @mbg.generated
     */
    private Boolean indisvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indcheckxmin
     *
     * @mbg.generated
     */
    private Boolean indcheckxmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisready
     *
     * @mbg.generated
     */
    private Boolean indisready;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indislive
     *
     * @mbg.generated
     */
    private Boolean indislive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indisreplident
     *
     * @mbg.generated
     */
    private Boolean indisreplident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indkey
     *
     * @mbg.generated
     */
    private Object indkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indcollation
     *
     * @mbg.generated
     */
    private Object indcollation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indclass
     *
     * @mbg.generated
     */
    private Object indclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indoption
     *
     * @mbg.generated
     */
    private Object indoption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indexprs
     *
     * @mbg.generated
     */
    private Object indexprs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_index.indpred
     *
     * @mbg.generated
     */
    private Object indpred;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_index
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indexrelid
     *
     * @return the value of pg_index.indexrelid
     *
     * @mbg.generated
     */
    public Long getIndexrelid() {
        return indexrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indexrelid
     *
     * @param indexrelid the value for pg_index.indexrelid
     *
     * @mbg.generated
     */
    public void setIndexrelid(Long indexrelid) {
        this.indexrelid = indexrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indrelid
     *
     * @return the value of pg_index.indrelid
     *
     * @mbg.generated
     */
    public Long getIndrelid() {
        return indrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indrelid
     *
     * @param indrelid the value for pg_index.indrelid
     *
     * @mbg.generated
     */
    public void setIndrelid(Long indrelid) {
        this.indrelid = indrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indnatts
     *
     * @return the value of pg_index.indnatts
     *
     * @mbg.generated
     */
    public Short getIndnatts() {
        return indnatts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indnatts
     *
     * @param indnatts the value for pg_index.indnatts
     *
     * @mbg.generated
     */
    public void setIndnatts(Short indnatts) {
        this.indnatts = indnatts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisunique
     *
     * @return the value of pg_index.indisunique
     *
     * @mbg.generated
     */
    public Boolean getIndisunique() {
        return indisunique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisunique
     *
     * @param indisunique the value for pg_index.indisunique
     *
     * @mbg.generated
     */
    public void setIndisunique(Boolean indisunique) {
        this.indisunique = indisunique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisprimary
     *
     * @return the value of pg_index.indisprimary
     *
     * @mbg.generated
     */
    public Boolean getIndisprimary() {
        return indisprimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisprimary
     *
     * @param indisprimary the value for pg_index.indisprimary
     *
     * @mbg.generated
     */
    public void setIndisprimary(Boolean indisprimary) {
        this.indisprimary = indisprimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisexclusion
     *
     * @return the value of pg_index.indisexclusion
     *
     * @mbg.generated
     */
    public Boolean getIndisexclusion() {
        return indisexclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisexclusion
     *
     * @param indisexclusion the value for pg_index.indisexclusion
     *
     * @mbg.generated
     */
    public void setIndisexclusion(Boolean indisexclusion) {
        this.indisexclusion = indisexclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indimmediate
     *
     * @return the value of pg_index.indimmediate
     *
     * @mbg.generated
     */
    public Boolean getIndimmediate() {
        return indimmediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indimmediate
     *
     * @param indimmediate the value for pg_index.indimmediate
     *
     * @mbg.generated
     */
    public void setIndimmediate(Boolean indimmediate) {
        this.indimmediate = indimmediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisclustered
     *
     * @return the value of pg_index.indisclustered
     *
     * @mbg.generated
     */
    public Boolean getIndisclustered() {
        return indisclustered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisclustered
     *
     * @param indisclustered the value for pg_index.indisclustered
     *
     * @mbg.generated
     */
    public void setIndisclustered(Boolean indisclustered) {
        this.indisclustered = indisclustered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisvalid
     *
     * @return the value of pg_index.indisvalid
     *
     * @mbg.generated
     */
    public Boolean getIndisvalid() {
        return indisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisvalid
     *
     * @param indisvalid the value for pg_index.indisvalid
     *
     * @mbg.generated
     */
    public void setIndisvalid(Boolean indisvalid) {
        this.indisvalid = indisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indcheckxmin
     *
     * @return the value of pg_index.indcheckxmin
     *
     * @mbg.generated
     */
    public Boolean getIndcheckxmin() {
        return indcheckxmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indcheckxmin
     *
     * @param indcheckxmin the value for pg_index.indcheckxmin
     *
     * @mbg.generated
     */
    public void setIndcheckxmin(Boolean indcheckxmin) {
        this.indcheckxmin = indcheckxmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisready
     *
     * @return the value of pg_index.indisready
     *
     * @mbg.generated
     */
    public Boolean getIndisready() {
        return indisready;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisready
     *
     * @param indisready the value for pg_index.indisready
     *
     * @mbg.generated
     */
    public void setIndisready(Boolean indisready) {
        this.indisready = indisready;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indislive
     *
     * @return the value of pg_index.indislive
     *
     * @mbg.generated
     */
    public Boolean getIndislive() {
        return indislive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indislive
     *
     * @param indislive the value for pg_index.indislive
     *
     * @mbg.generated
     */
    public void setIndislive(Boolean indislive) {
        this.indislive = indislive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indisreplident
     *
     * @return the value of pg_index.indisreplident
     *
     * @mbg.generated
     */
    public Boolean getIndisreplident() {
        return indisreplident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indisreplident
     *
     * @param indisreplident the value for pg_index.indisreplident
     *
     * @mbg.generated
     */
    public void setIndisreplident(Boolean indisreplident) {
        this.indisreplident = indisreplident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indkey
     *
     * @return the value of pg_index.indkey
     *
     * @mbg.generated
     */
    public Object getIndkey() {
        return indkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indkey
     *
     * @param indkey the value for pg_index.indkey
     *
     * @mbg.generated
     */
    public void setIndkey(Object indkey) {
        this.indkey = indkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indcollation
     *
     * @return the value of pg_index.indcollation
     *
     * @mbg.generated
     */
    public Object getIndcollation() {
        return indcollation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indcollation
     *
     * @param indcollation the value for pg_index.indcollation
     *
     * @mbg.generated
     */
    public void setIndcollation(Object indcollation) {
        this.indcollation = indcollation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indclass
     *
     * @return the value of pg_index.indclass
     *
     * @mbg.generated
     */
    public Object getIndclass() {
        return indclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indclass
     *
     * @param indclass the value for pg_index.indclass
     *
     * @mbg.generated
     */
    public void setIndclass(Object indclass) {
        this.indclass = indclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indoption
     *
     * @return the value of pg_index.indoption
     *
     * @mbg.generated
     */
    public Object getIndoption() {
        return indoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indoption
     *
     * @param indoption the value for pg_index.indoption
     *
     * @mbg.generated
     */
    public void setIndoption(Object indoption) {
        this.indoption = indoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indexprs
     *
     * @return the value of pg_index.indexprs
     *
     * @mbg.generated
     */
    public Object getIndexprs() {
        return indexprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indexprs
     *
     * @param indexprs the value for pg_index.indexprs
     *
     * @mbg.generated
     */
    public void setIndexprs(Object indexprs) {
        this.indexprs = indexprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_index.indpred
     *
     * @return the value of pg_index.indpred
     *
     * @mbg.generated
     */
    public Object getIndpred() {
        return indpred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_index.indpred
     *
     * @param indpred the value for pg_index.indpred
     *
     * @mbg.generated
     */
    public void setIndpred(Object indpred) {
        this.indpred = indpred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_index
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", indexrelid=").append(indexrelid);
        sb.append(", indrelid=").append(indrelid);
        sb.append(", indnatts=").append(indnatts);
        sb.append(", indisunique=").append(indisunique);
        sb.append(", indisprimary=").append(indisprimary);
        sb.append(", indisexclusion=").append(indisexclusion);
        sb.append(", indimmediate=").append(indimmediate);
        sb.append(", indisclustered=").append(indisclustered);
        sb.append(", indisvalid=").append(indisvalid);
        sb.append(", indcheckxmin=").append(indcheckxmin);
        sb.append(", indisready=").append(indisready);
        sb.append(", indislive=").append(indislive);
        sb.append(", indisreplident=").append(indisreplident);
        sb.append(", indkey=").append(indkey);
        sb.append(", indcollation=").append(indcollation);
        sb.append(", indclass=").append(indclass);
        sb.append(", indoption=").append(indoption);
        sb.append(", indexprs=").append(indexprs);
        sb.append(", indpred=").append(indpred);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}