package com.alva.arbook.entity;

import java.io.Serializable;

public class PgInitPrivs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_init_privs.objoid
     *
     * @mbg.generated
     */
    private Long objoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_init_privs.classoid
     *
     * @mbg.generated
     */
    private Long classoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_init_privs.objsubid
     *
     * @mbg.generated
     */
    private Integer objsubid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_init_privs.privtype
     *
     * @mbg.generated
     */
    private String privtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_init_privs.initprivs
     *
     * @mbg.generated
     */
    private Object initprivs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_init_privs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_init_privs.objoid
     *
     * @return the value of pg_init_privs.objoid
     *
     * @mbg.generated
     */
    public Long getObjoid() {
        return objoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_init_privs.objoid
     *
     * @param objoid the value for pg_init_privs.objoid
     *
     * @mbg.generated
     */
    public void setObjoid(Long objoid) {
        this.objoid = objoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_init_privs.classoid
     *
     * @return the value of pg_init_privs.classoid
     *
     * @mbg.generated
     */
    public Long getClassoid() {
        return classoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_init_privs.classoid
     *
     * @param classoid the value for pg_init_privs.classoid
     *
     * @mbg.generated
     */
    public void setClassoid(Long classoid) {
        this.classoid = classoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_init_privs.objsubid
     *
     * @return the value of pg_init_privs.objsubid
     *
     * @mbg.generated
     */
    public Integer getObjsubid() {
        return objsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_init_privs.objsubid
     *
     * @param objsubid the value for pg_init_privs.objsubid
     *
     * @mbg.generated
     */
    public void setObjsubid(Integer objsubid) {
        this.objsubid = objsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_init_privs.privtype
     *
     * @return the value of pg_init_privs.privtype
     *
     * @mbg.generated
     */
    public String getPrivtype() {
        return privtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_init_privs.privtype
     *
     * @param privtype the value for pg_init_privs.privtype
     *
     * @mbg.generated
     */
    public void setPrivtype(String privtype) {
        this.privtype = privtype == null ? null : privtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_init_privs.initprivs
     *
     * @return the value of pg_init_privs.initprivs
     *
     * @mbg.generated
     */
    public Object getInitprivs() {
        return initprivs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_init_privs.initprivs
     *
     * @param initprivs the value for pg_init_privs.initprivs
     *
     * @mbg.generated
     */
    public void setInitprivs(Object initprivs) {
        this.initprivs = initprivs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_init_privs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", objoid=").append(objoid);
        sb.append(", classoid=").append(classoid);
        sb.append(", objsubid=").append(objsubid);
        sb.append(", privtype=").append(privtype);
        sb.append(", initprivs=").append(initprivs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}