package com.alva.arbook.entity;

import java.io.Serializable;

public class PgLanguage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanname
     *
     * @mbg.generated
     */
    private String lanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanowner
     *
     * @mbg.generated
     */
    private Long lanowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanispl
     *
     * @mbg.generated
     */
    private Boolean lanispl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanpltrusted
     *
     * @mbg.generated
     */
    private Boolean lanpltrusted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanplcallfoid
     *
     * @mbg.generated
     */
    private Long lanplcallfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.laninline
     *
     * @mbg.generated
     */
    private Long laninline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanvalidator
     *
     * @mbg.generated
     */
    private Long lanvalidator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_language.lanacl
     *
     * @mbg.generated
     */
    private Object lanacl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_language
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanname
     *
     * @return the value of pg_language.lanname
     *
     * @mbg.generated
     */
    public String getLanname() {
        return lanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanname
     *
     * @param lanname the value for pg_language.lanname
     *
     * @mbg.generated
     */
    public void setLanname(String lanname) {
        this.lanname = lanname == null ? null : lanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanowner
     *
     * @return the value of pg_language.lanowner
     *
     * @mbg.generated
     */
    public Long getLanowner() {
        return lanowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanowner
     *
     * @param lanowner the value for pg_language.lanowner
     *
     * @mbg.generated
     */
    public void setLanowner(Long lanowner) {
        this.lanowner = lanowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanispl
     *
     * @return the value of pg_language.lanispl
     *
     * @mbg.generated
     */
    public Boolean getLanispl() {
        return lanispl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanispl
     *
     * @param lanispl the value for pg_language.lanispl
     *
     * @mbg.generated
     */
    public void setLanispl(Boolean lanispl) {
        this.lanispl = lanispl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanpltrusted
     *
     * @return the value of pg_language.lanpltrusted
     *
     * @mbg.generated
     */
    public Boolean getLanpltrusted() {
        return lanpltrusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanpltrusted
     *
     * @param lanpltrusted the value for pg_language.lanpltrusted
     *
     * @mbg.generated
     */
    public void setLanpltrusted(Boolean lanpltrusted) {
        this.lanpltrusted = lanpltrusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanplcallfoid
     *
     * @return the value of pg_language.lanplcallfoid
     *
     * @mbg.generated
     */
    public Long getLanplcallfoid() {
        return lanplcallfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanplcallfoid
     *
     * @param lanplcallfoid the value for pg_language.lanplcallfoid
     *
     * @mbg.generated
     */
    public void setLanplcallfoid(Long lanplcallfoid) {
        this.lanplcallfoid = lanplcallfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.laninline
     *
     * @return the value of pg_language.laninline
     *
     * @mbg.generated
     */
    public Long getLaninline() {
        return laninline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.laninline
     *
     * @param laninline the value for pg_language.laninline
     *
     * @mbg.generated
     */
    public void setLaninline(Long laninline) {
        this.laninline = laninline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanvalidator
     *
     * @return the value of pg_language.lanvalidator
     *
     * @mbg.generated
     */
    public Long getLanvalidator() {
        return lanvalidator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanvalidator
     *
     * @param lanvalidator the value for pg_language.lanvalidator
     *
     * @mbg.generated
     */
    public void setLanvalidator(Long lanvalidator) {
        this.lanvalidator = lanvalidator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_language.lanacl
     *
     * @return the value of pg_language.lanacl
     *
     * @mbg.generated
     */
    public Object getLanacl() {
        return lanacl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_language.lanacl
     *
     * @param lanacl the value for pg_language.lanacl
     *
     * @mbg.generated
     */
    public void setLanacl(Object lanacl) {
        this.lanacl = lanacl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_language
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lanname=").append(lanname);
        sb.append(", lanowner=").append(lanowner);
        sb.append(", lanispl=").append(lanispl);
        sb.append(", lanpltrusted=").append(lanpltrusted);
        sb.append(", lanplcallfoid=").append(lanplcallfoid);
        sb.append(", laninline=").append(laninline);
        sb.append(", lanvalidator=").append(lanvalidator);
        sb.append(", lanacl=").append(lanacl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}