package com.alva.arbook.entity;

import java.io.Serializable;

public class PgPolicy implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polname
     *
     * @mbg.generated
     */
    private String polname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polrelid
     *
     * @mbg.generated
     */
    private Long polrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polcmd
     *
     * @mbg.generated
     */
    private String polcmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polpermissive
     *
     * @mbg.generated
     */
    private Boolean polpermissive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polroles
     *
     * @mbg.generated
     */
    private Object polroles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polqual
     *
     * @mbg.generated
     */
    private Object polqual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policy.polwithcheck
     *
     * @mbg.generated
     */
    private Object polwithcheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_policy
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polname
     *
     * @return the value of pg_policy.polname
     *
     * @mbg.generated
     */
    public String getPolname() {
        return polname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polname
     *
     * @param polname the value for pg_policy.polname
     *
     * @mbg.generated
     */
    public void setPolname(String polname) {
        this.polname = polname == null ? null : polname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polrelid
     *
     * @return the value of pg_policy.polrelid
     *
     * @mbg.generated
     */
    public Long getPolrelid() {
        return polrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polrelid
     *
     * @param polrelid the value for pg_policy.polrelid
     *
     * @mbg.generated
     */
    public void setPolrelid(Long polrelid) {
        this.polrelid = polrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polcmd
     *
     * @return the value of pg_policy.polcmd
     *
     * @mbg.generated
     */
    public String getPolcmd() {
        return polcmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polcmd
     *
     * @param polcmd the value for pg_policy.polcmd
     *
     * @mbg.generated
     */
    public void setPolcmd(String polcmd) {
        this.polcmd = polcmd == null ? null : polcmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polpermissive
     *
     * @return the value of pg_policy.polpermissive
     *
     * @mbg.generated
     */
    public Boolean getPolpermissive() {
        return polpermissive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polpermissive
     *
     * @param polpermissive the value for pg_policy.polpermissive
     *
     * @mbg.generated
     */
    public void setPolpermissive(Boolean polpermissive) {
        this.polpermissive = polpermissive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polroles
     *
     * @return the value of pg_policy.polroles
     *
     * @mbg.generated
     */
    public Object getPolroles() {
        return polroles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polroles
     *
     * @param polroles the value for pg_policy.polroles
     *
     * @mbg.generated
     */
    public void setPolroles(Object polroles) {
        this.polroles = polroles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polqual
     *
     * @return the value of pg_policy.polqual
     *
     * @mbg.generated
     */
    public Object getPolqual() {
        return polqual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polqual
     *
     * @param polqual the value for pg_policy.polqual
     *
     * @mbg.generated
     */
    public void setPolqual(Object polqual) {
        this.polqual = polqual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policy.polwithcheck
     *
     * @return the value of pg_policy.polwithcheck
     *
     * @mbg.generated
     */
    public Object getPolwithcheck() {
        return polwithcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policy.polwithcheck
     *
     * @param polwithcheck the value for pg_policy.polwithcheck
     *
     * @mbg.generated
     */
    public void setPolwithcheck(Object polwithcheck) {
        this.polwithcheck = polwithcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_policy
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", polname=").append(polname);
        sb.append(", polrelid=").append(polrelid);
        sb.append(", polcmd=").append(polcmd);
        sb.append(", polpermissive=").append(polpermissive);
        sb.append(", polroles=").append(polroles);
        sb.append(", polqual=").append(polqual);
        sb.append(", polwithcheck=").append(polwithcheck);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}