package com.alva.arbook.entity;

import java.io.Serializable;

public class PgPolicies implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.schemaname
     *
     * @mbg.generated
     */
    private String schemaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.tablename
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.policyname
     *
     * @mbg.generated
     */
    private String policyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.permissive
     *
     * @mbg.generated
     */
    private String permissive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.roles
     *
     * @mbg.generated
     */
    private Object roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.cmd
     *
     * @mbg.generated
     */
    private String cmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.qual
     *
     * @mbg.generated
     */
    private String qual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_policies.with_check
     *
     * @mbg.generated
     */
    private String withCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_policies
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.schemaname
     *
     * @return the value of pg_policies.schemaname
     *
     * @mbg.generated
     */
    public String getSchemaname() {
        return schemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.schemaname
     *
     * @param schemaname the value for pg_policies.schemaname
     *
     * @mbg.generated
     */
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname == null ? null : schemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.tablename
     *
     * @return the value of pg_policies.tablename
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.tablename
     *
     * @param tablename the value for pg_policies.tablename
     *
     * @mbg.generated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.policyname
     *
     * @return the value of pg_policies.policyname
     *
     * @mbg.generated
     */
    public String getPolicyname() {
        return policyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.policyname
     *
     * @param policyname the value for pg_policies.policyname
     *
     * @mbg.generated
     */
    public void setPolicyname(String policyname) {
        this.policyname = policyname == null ? null : policyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.permissive
     *
     * @return the value of pg_policies.permissive
     *
     * @mbg.generated
     */
    public String getPermissive() {
        return permissive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.permissive
     *
     * @param permissive the value for pg_policies.permissive
     *
     * @mbg.generated
     */
    public void setPermissive(String permissive) {
        this.permissive = permissive == null ? null : permissive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.roles
     *
     * @return the value of pg_policies.roles
     *
     * @mbg.generated
     */
    public Object getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.roles
     *
     * @param roles the value for pg_policies.roles
     *
     * @mbg.generated
     */
    public void setRoles(Object roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.cmd
     *
     * @return the value of pg_policies.cmd
     *
     * @mbg.generated
     */
    public String getCmd() {
        return cmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.cmd
     *
     * @param cmd the value for pg_policies.cmd
     *
     * @mbg.generated
     */
    public void setCmd(String cmd) {
        this.cmd = cmd == null ? null : cmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.qual
     *
     * @return the value of pg_policies.qual
     *
     * @mbg.generated
     */
    public String getQual() {
        return qual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.qual
     *
     * @param qual the value for pg_policies.qual
     *
     * @mbg.generated
     */
    public void setQual(String qual) {
        this.qual = qual == null ? null : qual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_policies.with_check
     *
     * @return the value of pg_policies.with_check
     *
     * @mbg.generated
     */
    public String getWithCheck() {
        return withCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_policies.with_check
     *
     * @param withCheck the value for pg_policies.with_check
     *
     * @mbg.generated
     */
    public void setWithCheck(String withCheck) {
        this.withCheck = withCheck == null ? null : withCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_policies
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schemaname=").append(schemaname);
        sb.append(", tablename=").append(tablename);
        sb.append(", policyname=").append(policyname);
        sb.append(", permissive=").append(permissive);
        sb.append(", roles=").append(roles);
        sb.append(", cmd=").append(cmd);
        sb.append(", qual=").append(qual);
        sb.append(", withCheck=").append(withCheck);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}