package com.alva.arbook.entity;

import java.io.Serializable;

public class PgReplicationOrigin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_replication_origin.roident
     *
     * @mbg.generated
     */
    private Long roident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_replication_origin.roname
     *
     * @mbg.generated
     */
    private String roname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_replication_origin
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_replication_origin.roident
     *
     * @return the value of pg_replication_origin.roident
     *
     * @mbg.generated
     */
    public Long getRoident() {
        return roident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_replication_origin.roident
     *
     * @param roident the value for pg_replication_origin.roident
     *
     * @mbg.generated
     */
    public void setRoident(Long roident) {
        this.roident = roident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_replication_origin.roname
     *
     * @return the value of pg_replication_origin.roname
     *
     * @mbg.generated
     */
    public String getRoname() {
        return roname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_replication_origin.roname
     *
     * @param roname the value for pg_replication_origin.roname
     *
     * @mbg.generated
     */
    public void setRoname(String roname) {
        this.roname = roname == null ? null : roname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_replication_origin
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roident=").append(roident);
        sb.append(", roname=").append(roname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}