package com.alva.arbook.entity;

import java.io.Serializable;

public class PgRewrite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.rulename
     *
     * @mbg.generated
     */
    private String rulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.ev_class
     *
     * @mbg.generated
     */
    private Long evClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.ev_type
     *
     * @mbg.generated
     */
    private String evType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.ev_enabled
     *
     * @mbg.generated
     */
    private String evEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.is_instead
     *
     * @mbg.generated
     */
    private Boolean isInstead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.ev_qual
     *
     * @mbg.generated
     */
    private Object evQual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_rewrite.ev_action
     *
     * @mbg.generated
     */
    private Object evAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_rewrite
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.rulename
     *
     * @return the value of pg_rewrite.rulename
     *
     * @mbg.generated
     */
    public String getRulename() {
        return rulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.rulename
     *
     * @param rulename the value for pg_rewrite.rulename
     *
     * @mbg.generated
     */
    public void setRulename(String rulename) {
        this.rulename = rulename == null ? null : rulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.ev_class
     *
     * @return the value of pg_rewrite.ev_class
     *
     * @mbg.generated
     */
    public Long getEvClass() {
        return evClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.ev_class
     *
     * @param evClass the value for pg_rewrite.ev_class
     *
     * @mbg.generated
     */
    public void setEvClass(Long evClass) {
        this.evClass = evClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.ev_type
     *
     * @return the value of pg_rewrite.ev_type
     *
     * @mbg.generated
     */
    public String getEvType() {
        return evType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.ev_type
     *
     * @param evType the value for pg_rewrite.ev_type
     *
     * @mbg.generated
     */
    public void setEvType(String evType) {
        this.evType = evType == null ? null : evType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.ev_enabled
     *
     * @return the value of pg_rewrite.ev_enabled
     *
     * @mbg.generated
     */
    public String getEvEnabled() {
        return evEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.ev_enabled
     *
     * @param evEnabled the value for pg_rewrite.ev_enabled
     *
     * @mbg.generated
     */
    public void setEvEnabled(String evEnabled) {
        this.evEnabled = evEnabled == null ? null : evEnabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.is_instead
     *
     * @return the value of pg_rewrite.is_instead
     *
     * @mbg.generated
     */
    public Boolean getIsInstead() {
        return isInstead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.is_instead
     *
     * @param isInstead the value for pg_rewrite.is_instead
     *
     * @mbg.generated
     */
    public void setIsInstead(Boolean isInstead) {
        this.isInstead = isInstead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.ev_qual
     *
     * @return the value of pg_rewrite.ev_qual
     *
     * @mbg.generated
     */
    public Object getEvQual() {
        return evQual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.ev_qual
     *
     * @param evQual the value for pg_rewrite.ev_qual
     *
     * @mbg.generated
     */
    public void setEvQual(Object evQual) {
        this.evQual = evQual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_rewrite.ev_action
     *
     * @return the value of pg_rewrite.ev_action
     *
     * @mbg.generated
     */
    public Object getEvAction() {
        return evAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_rewrite.ev_action
     *
     * @param evAction the value for pg_rewrite.ev_action
     *
     * @mbg.generated
     */
    public void setEvAction(Object evAction) {
        this.evAction = evAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_rewrite
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rulename=").append(rulename);
        sb.append(", evClass=").append(evClass);
        sb.append(", evType=").append(evType);
        sb.append(", evEnabled=").append(evEnabled);
        sb.append(", isInstead=").append(isInstead);
        sb.append(", evQual=").append(evQual);
        sb.append(", evAction=").append(evAction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}