package com.alva.arbook.entity;

import java.io.Serializable;

public class PgStatUserFunctions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.funcid
     *
     * @mbg.generated
     */
    private Long funcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.schemaname
     *
     * @mbg.generated
     */
    private String schemaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.funcname
     *
     * @mbg.generated
     */
    private String funcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.calls
     *
     * @mbg.generated
     */
    private Long calls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.total_time
     *
     * @mbg.generated
     */
    private Double totalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_user_functions.self_time
     *
     * @mbg.generated
     */
    private Double selfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_stat_user_functions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.funcid
     *
     * @return the value of pg_stat_user_functions.funcid
     *
     * @mbg.generated
     */
    public Long getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.funcid
     *
     * @param funcid the value for pg_stat_user_functions.funcid
     *
     * @mbg.generated
     */
    public void setFuncid(Long funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.schemaname
     *
     * @return the value of pg_stat_user_functions.schemaname
     *
     * @mbg.generated
     */
    public String getSchemaname() {
        return schemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.schemaname
     *
     * @param schemaname the value for pg_stat_user_functions.schemaname
     *
     * @mbg.generated
     */
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname == null ? null : schemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.funcname
     *
     * @return the value of pg_stat_user_functions.funcname
     *
     * @mbg.generated
     */
    public String getFuncname() {
        return funcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.funcname
     *
     * @param funcname the value for pg_stat_user_functions.funcname
     *
     * @mbg.generated
     */
    public void setFuncname(String funcname) {
        this.funcname = funcname == null ? null : funcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.calls
     *
     * @return the value of pg_stat_user_functions.calls
     *
     * @mbg.generated
     */
    public Long getCalls() {
        return calls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.calls
     *
     * @param calls the value for pg_stat_user_functions.calls
     *
     * @mbg.generated
     */
    public void setCalls(Long calls) {
        this.calls = calls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.total_time
     *
     * @return the value of pg_stat_user_functions.total_time
     *
     * @mbg.generated
     */
    public Double getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.total_time
     *
     * @param totalTime the value for pg_stat_user_functions.total_time
     *
     * @mbg.generated
     */
    public void setTotalTime(Double totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_user_functions.self_time
     *
     * @return the value of pg_stat_user_functions.self_time
     *
     * @mbg.generated
     */
    public Double getSelfTime() {
        return selfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_user_functions.self_time
     *
     * @param selfTime the value for pg_stat_user_functions.self_time
     *
     * @mbg.generated
     */
    public void setSelfTime(Double selfTime) {
        this.selfTime = selfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_user_functions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", funcid=").append(funcid);
        sb.append(", schemaname=").append(schemaname);
        sb.append(", funcname=").append(funcname);
        sb.append(", calls=").append(calls);
        sb.append(", totalTime=").append(totalTime);
        sb.append(", selfTime=").append(selfTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}