package com.alva.arbook.entity;

import java.io.Serializable;
import java.util.Date;

public class PgStatSysTables implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.relid
     *
     * @mbg.generated
     */
    private Long relid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.schemaname
     *
     * @mbg.generated
     */
    private String schemaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.relname
     *
     * @mbg.generated
     */
    private String relname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.seq_scan
     *
     * @mbg.generated
     */
    private Long seqScan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.seq_tup_read
     *
     * @mbg.generated
     */
    private Long seqTupRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.idx_scan
     *
     * @mbg.generated
     */
    private Long idxScan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.idx_tup_fetch
     *
     * @mbg.generated
     */
    private Long idxTupFetch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_tup_ins
     *
     * @mbg.generated
     */
    private Long nTupIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_tup_upd
     *
     * @mbg.generated
     */
    private Long nTupUpd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_tup_del
     *
     * @mbg.generated
     */
    private Long nTupDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_tup_hot_upd
     *
     * @mbg.generated
     */
    private Long nTupHotUpd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_live_tup
     *
     * @mbg.generated
     */
    private Long nLiveTup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_dead_tup
     *
     * @mbg.generated
     */
    private Long nDeadTup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.n_mod_since_analyze
     *
     * @mbg.generated
     */
    private Long nModSinceAnalyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.last_vacuum
     *
     * @mbg.generated
     */
    private Date lastVacuum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.last_autovacuum
     *
     * @mbg.generated
     */
    private Date lastAutovacuum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.last_analyze
     *
     * @mbg.generated
     */
    private Date lastAnalyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.last_autoanalyze
     *
     * @mbg.generated
     */
    private Date lastAutoanalyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.vacuum_count
     *
     * @mbg.generated
     */
    private Long vacuumCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.autovacuum_count
     *
     * @mbg.generated
     */
    private Long autovacuumCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.analyze_count
     *
     * @mbg.generated
     */
    private Long analyzeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_sys_tables.autoanalyze_count
     *
     * @mbg.generated
     */
    private Long autoanalyzeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_stat_sys_tables
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.relid
     *
     * @return the value of pg_stat_sys_tables.relid
     *
     * @mbg.generated
     */
    public Long getRelid() {
        return relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.relid
     *
     * @param relid the value for pg_stat_sys_tables.relid
     *
     * @mbg.generated
     */
    public void setRelid(Long relid) {
        this.relid = relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.schemaname
     *
     * @return the value of pg_stat_sys_tables.schemaname
     *
     * @mbg.generated
     */
    public String getSchemaname() {
        return schemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.schemaname
     *
     * @param schemaname the value for pg_stat_sys_tables.schemaname
     *
     * @mbg.generated
     */
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname == null ? null : schemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.relname
     *
     * @return the value of pg_stat_sys_tables.relname
     *
     * @mbg.generated
     */
    public String getRelname() {
        return relname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.relname
     *
     * @param relname the value for pg_stat_sys_tables.relname
     *
     * @mbg.generated
     */
    public void setRelname(String relname) {
        this.relname = relname == null ? null : relname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.seq_scan
     *
     * @return the value of pg_stat_sys_tables.seq_scan
     *
     * @mbg.generated
     */
    public Long getSeqScan() {
        return seqScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.seq_scan
     *
     * @param seqScan the value for pg_stat_sys_tables.seq_scan
     *
     * @mbg.generated
     */
    public void setSeqScan(Long seqScan) {
        this.seqScan = seqScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.seq_tup_read
     *
     * @return the value of pg_stat_sys_tables.seq_tup_read
     *
     * @mbg.generated
     */
    public Long getSeqTupRead() {
        return seqTupRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.seq_tup_read
     *
     * @param seqTupRead the value for pg_stat_sys_tables.seq_tup_read
     *
     * @mbg.generated
     */
    public void setSeqTupRead(Long seqTupRead) {
        this.seqTupRead = seqTupRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.idx_scan
     *
     * @return the value of pg_stat_sys_tables.idx_scan
     *
     * @mbg.generated
     */
    public Long getIdxScan() {
        return idxScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.idx_scan
     *
     * @param idxScan the value for pg_stat_sys_tables.idx_scan
     *
     * @mbg.generated
     */
    public void setIdxScan(Long idxScan) {
        this.idxScan = idxScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.idx_tup_fetch
     *
     * @return the value of pg_stat_sys_tables.idx_tup_fetch
     *
     * @mbg.generated
     */
    public Long getIdxTupFetch() {
        return idxTupFetch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.idx_tup_fetch
     *
     * @param idxTupFetch the value for pg_stat_sys_tables.idx_tup_fetch
     *
     * @mbg.generated
     */
    public void setIdxTupFetch(Long idxTupFetch) {
        this.idxTupFetch = idxTupFetch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_tup_ins
     *
     * @return the value of pg_stat_sys_tables.n_tup_ins
     *
     * @mbg.generated
     */
    public Long getnTupIns() {
        return nTupIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_tup_ins
     *
     * @param nTupIns the value for pg_stat_sys_tables.n_tup_ins
     *
     * @mbg.generated
     */
    public void setnTupIns(Long nTupIns) {
        this.nTupIns = nTupIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_tup_upd
     *
     * @return the value of pg_stat_sys_tables.n_tup_upd
     *
     * @mbg.generated
     */
    public Long getnTupUpd() {
        return nTupUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_tup_upd
     *
     * @param nTupUpd the value for pg_stat_sys_tables.n_tup_upd
     *
     * @mbg.generated
     */
    public void setnTupUpd(Long nTupUpd) {
        this.nTupUpd = nTupUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_tup_del
     *
     * @return the value of pg_stat_sys_tables.n_tup_del
     *
     * @mbg.generated
     */
    public Long getnTupDel() {
        return nTupDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_tup_del
     *
     * @param nTupDel the value for pg_stat_sys_tables.n_tup_del
     *
     * @mbg.generated
     */
    public void setnTupDel(Long nTupDel) {
        this.nTupDel = nTupDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_tup_hot_upd
     *
     * @return the value of pg_stat_sys_tables.n_tup_hot_upd
     *
     * @mbg.generated
     */
    public Long getnTupHotUpd() {
        return nTupHotUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_tup_hot_upd
     *
     * @param nTupHotUpd the value for pg_stat_sys_tables.n_tup_hot_upd
     *
     * @mbg.generated
     */
    public void setnTupHotUpd(Long nTupHotUpd) {
        this.nTupHotUpd = nTupHotUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_live_tup
     *
     * @return the value of pg_stat_sys_tables.n_live_tup
     *
     * @mbg.generated
     */
    public Long getnLiveTup() {
        return nLiveTup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_live_tup
     *
     * @param nLiveTup the value for pg_stat_sys_tables.n_live_tup
     *
     * @mbg.generated
     */
    public void setnLiveTup(Long nLiveTup) {
        this.nLiveTup = nLiveTup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_dead_tup
     *
     * @return the value of pg_stat_sys_tables.n_dead_tup
     *
     * @mbg.generated
     */
    public Long getnDeadTup() {
        return nDeadTup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_dead_tup
     *
     * @param nDeadTup the value for pg_stat_sys_tables.n_dead_tup
     *
     * @mbg.generated
     */
    public void setnDeadTup(Long nDeadTup) {
        this.nDeadTup = nDeadTup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.n_mod_since_analyze
     *
     * @return the value of pg_stat_sys_tables.n_mod_since_analyze
     *
     * @mbg.generated
     */
    public Long getnModSinceAnalyze() {
        return nModSinceAnalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.n_mod_since_analyze
     *
     * @param nModSinceAnalyze the value for pg_stat_sys_tables.n_mod_since_analyze
     *
     * @mbg.generated
     */
    public void setnModSinceAnalyze(Long nModSinceAnalyze) {
        this.nModSinceAnalyze = nModSinceAnalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.last_vacuum
     *
     * @return the value of pg_stat_sys_tables.last_vacuum
     *
     * @mbg.generated
     */
    public Date getLastVacuum() {
        return lastVacuum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.last_vacuum
     *
     * @param lastVacuum the value for pg_stat_sys_tables.last_vacuum
     *
     * @mbg.generated
     */
    public void setLastVacuum(Date lastVacuum) {
        this.lastVacuum = lastVacuum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.last_autovacuum
     *
     * @return the value of pg_stat_sys_tables.last_autovacuum
     *
     * @mbg.generated
     */
    public Date getLastAutovacuum() {
        return lastAutovacuum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.last_autovacuum
     *
     * @param lastAutovacuum the value for pg_stat_sys_tables.last_autovacuum
     *
     * @mbg.generated
     */
    public void setLastAutovacuum(Date lastAutovacuum) {
        this.lastAutovacuum = lastAutovacuum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.last_analyze
     *
     * @return the value of pg_stat_sys_tables.last_analyze
     *
     * @mbg.generated
     */
    public Date getLastAnalyze() {
        return lastAnalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.last_analyze
     *
     * @param lastAnalyze the value for pg_stat_sys_tables.last_analyze
     *
     * @mbg.generated
     */
    public void setLastAnalyze(Date lastAnalyze) {
        this.lastAnalyze = lastAnalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.last_autoanalyze
     *
     * @return the value of pg_stat_sys_tables.last_autoanalyze
     *
     * @mbg.generated
     */
    public Date getLastAutoanalyze() {
        return lastAutoanalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.last_autoanalyze
     *
     * @param lastAutoanalyze the value for pg_stat_sys_tables.last_autoanalyze
     *
     * @mbg.generated
     */
    public void setLastAutoanalyze(Date lastAutoanalyze) {
        this.lastAutoanalyze = lastAutoanalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.vacuum_count
     *
     * @return the value of pg_stat_sys_tables.vacuum_count
     *
     * @mbg.generated
     */
    public Long getVacuumCount() {
        return vacuumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.vacuum_count
     *
     * @param vacuumCount the value for pg_stat_sys_tables.vacuum_count
     *
     * @mbg.generated
     */
    public void setVacuumCount(Long vacuumCount) {
        this.vacuumCount = vacuumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.autovacuum_count
     *
     * @return the value of pg_stat_sys_tables.autovacuum_count
     *
     * @mbg.generated
     */
    public Long getAutovacuumCount() {
        return autovacuumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.autovacuum_count
     *
     * @param autovacuumCount the value for pg_stat_sys_tables.autovacuum_count
     *
     * @mbg.generated
     */
    public void setAutovacuumCount(Long autovacuumCount) {
        this.autovacuumCount = autovacuumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.analyze_count
     *
     * @return the value of pg_stat_sys_tables.analyze_count
     *
     * @mbg.generated
     */
    public Long getAnalyzeCount() {
        return analyzeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.analyze_count
     *
     * @param analyzeCount the value for pg_stat_sys_tables.analyze_count
     *
     * @mbg.generated
     */
    public void setAnalyzeCount(Long analyzeCount) {
        this.analyzeCount = analyzeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_sys_tables.autoanalyze_count
     *
     * @return the value of pg_stat_sys_tables.autoanalyze_count
     *
     * @mbg.generated
     */
    public Long getAutoanalyzeCount() {
        return autoanalyzeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_sys_tables.autoanalyze_count
     *
     * @param autoanalyzeCount the value for pg_stat_sys_tables.autoanalyze_count
     *
     * @mbg.generated
     */
    public void setAutoanalyzeCount(Long autoanalyzeCount) {
        this.autoanalyzeCount = autoanalyzeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_sys_tables
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", relid=").append(relid);
        sb.append(", schemaname=").append(schemaname);
        sb.append(", relname=").append(relname);
        sb.append(", seqScan=").append(seqScan);
        sb.append(", seqTupRead=").append(seqTupRead);
        sb.append(", idxScan=").append(idxScan);
        sb.append(", idxTupFetch=").append(idxTupFetch);
        sb.append(", nTupIns=").append(nTupIns);
        sb.append(", nTupUpd=").append(nTupUpd);
        sb.append(", nTupDel=").append(nTupDel);
        sb.append(", nTupHotUpd=").append(nTupHotUpd);
        sb.append(", nLiveTup=").append(nLiveTup);
        sb.append(", nDeadTup=").append(nDeadTup);
        sb.append(", nModSinceAnalyze=").append(nModSinceAnalyze);
        sb.append(", lastVacuum=").append(lastVacuum);
        sb.append(", lastAutovacuum=").append(lastAutovacuum);
        sb.append(", lastAnalyze=").append(lastAnalyze);
        sb.append(", lastAutoanalyze=").append(lastAutoanalyze);
        sb.append(", vacuumCount=").append(vacuumCount);
        sb.append(", autovacuumCount=").append(autovacuumCount);
        sb.append(", analyzeCount=").append(analyzeCount);
        sb.append(", autoanalyzeCount=").append(autoanalyzeCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}