package com.alva.arbook.entity;

import java.io.Serializable;
import java.util.Date;

public class PgStatReplication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.usesysid
     *
     * @mbg.generated
     */
    private Long usesysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.usename
     *
     * @mbg.generated
     */
    private String usename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.application_name
     *
     * @mbg.generated
     */
    private String applicationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.client_addr
     *
     * @mbg.generated
     */
    private Object clientAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.client_hostname
     *
     * @mbg.generated
     */
    private String clientHostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.client_port
     *
     * @mbg.generated
     */
    private Integer clientPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.backend_start
     *
     * @mbg.generated
     */
    private Date backendStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.backend_xmin
     *
     * @mbg.generated
     */
    private Object backendXmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.sent_lsn
     *
     * @mbg.generated
     */
    private Object sentLsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.write_lsn
     *
     * @mbg.generated
     */
    private Object writeLsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.flush_lsn
     *
     * @mbg.generated
     */
    private Object flushLsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.replay_lsn
     *
     * @mbg.generated
     */
    private Object replayLsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.write_lag
     *
     * @mbg.generated
     */
    private Object writeLag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.flush_lag
     *
     * @mbg.generated
     */
    private Object flushLag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.replay_lag
     *
     * @mbg.generated
     */
    private Object replayLag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.sync_priority
     *
     * @mbg.generated
     */
    private Integer syncPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_replication.sync_state
     *
     * @mbg.generated
     */
    private String syncState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_stat_replication
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.pid
     *
     * @return the value of pg_stat_replication.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.pid
     *
     * @param pid the value for pg_stat_replication.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.usesysid
     *
     * @return the value of pg_stat_replication.usesysid
     *
     * @mbg.generated
     */
    public Long getUsesysid() {
        return usesysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.usesysid
     *
     * @param usesysid the value for pg_stat_replication.usesysid
     *
     * @mbg.generated
     */
    public void setUsesysid(Long usesysid) {
        this.usesysid = usesysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.usename
     *
     * @return the value of pg_stat_replication.usename
     *
     * @mbg.generated
     */
    public String getUsename() {
        return usename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.usename
     *
     * @param usename the value for pg_stat_replication.usename
     *
     * @mbg.generated
     */
    public void setUsename(String usename) {
        this.usename = usename == null ? null : usename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.application_name
     *
     * @return the value of pg_stat_replication.application_name
     *
     * @mbg.generated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.application_name
     *
     * @param applicationName the value for pg_stat_replication.application_name
     *
     * @mbg.generated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.client_addr
     *
     * @return the value of pg_stat_replication.client_addr
     *
     * @mbg.generated
     */
    public Object getClientAddr() {
        return clientAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.client_addr
     *
     * @param clientAddr the value for pg_stat_replication.client_addr
     *
     * @mbg.generated
     */
    public void setClientAddr(Object clientAddr) {
        this.clientAddr = clientAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.client_hostname
     *
     * @return the value of pg_stat_replication.client_hostname
     *
     * @mbg.generated
     */
    public String getClientHostname() {
        return clientHostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.client_hostname
     *
     * @param clientHostname the value for pg_stat_replication.client_hostname
     *
     * @mbg.generated
     */
    public void setClientHostname(String clientHostname) {
        this.clientHostname = clientHostname == null ? null : clientHostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.client_port
     *
     * @return the value of pg_stat_replication.client_port
     *
     * @mbg.generated
     */
    public Integer getClientPort() {
        return clientPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.client_port
     *
     * @param clientPort the value for pg_stat_replication.client_port
     *
     * @mbg.generated
     */
    public void setClientPort(Integer clientPort) {
        this.clientPort = clientPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.backend_start
     *
     * @return the value of pg_stat_replication.backend_start
     *
     * @mbg.generated
     */
    public Date getBackendStart() {
        return backendStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.backend_start
     *
     * @param backendStart the value for pg_stat_replication.backend_start
     *
     * @mbg.generated
     */
    public void setBackendStart(Date backendStart) {
        this.backendStart = backendStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.backend_xmin
     *
     * @return the value of pg_stat_replication.backend_xmin
     *
     * @mbg.generated
     */
    public Object getBackendXmin() {
        return backendXmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.backend_xmin
     *
     * @param backendXmin the value for pg_stat_replication.backend_xmin
     *
     * @mbg.generated
     */
    public void setBackendXmin(Object backendXmin) {
        this.backendXmin = backendXmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.state
     *
     * @return the value of pg_stat_replication.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.state
     *
     * @param state the value for pg_stat_replication.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.sent_lsn
     *
     * @return the value of pg_stat_replication.sent_lsn
     *
     * @mbg.generated
     */
    public Object getSentLsn() {
        return sentLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.sent_lsn
     *
     * @param sentLsn the value for pg_stat_replication.sent_lsn
     *
     * @mbg.generated
     */
    public void setSentLsn(Object sentLsn) {
        this.sentLsn = sentLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.write_lsn
     *
     * @return the value of pg_stat_replication.write_lsn
     *
     * @mbg.generated
     */
    public Object getWriteLsn() {
        return writeLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.write_lsn
     *
     * @param writeLsn the value for pg_stat_replication.write_lsn
     *
     * @mbg.generated
     */
    public void setWriteLsn(Object writeLsn) {
        this.writeLsn = writeLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.flush_lsn
     *
     * @return the value of pg_stat_replication.flush_lsn
     *
     * @mbg.generated
     */
    public Object getFlushLsn() {
        return flushLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.flush_lsn
     *
     * @param flushLsn the value for pg_stat_replication.flush_lsn
     *
     * @mbg.generated
     */
    public void setFlushLsn(Object flushLsn) {
        this.flushLsn = flushLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.replay_lsn
     *
     * @return the value of pg_stat_replication.replay_lsn
     *
     * @mbg.generated
     */
    public Object getReplayLsn() {
        return replayLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.replay_lsn
     *
     * @param replayLsn the value for pg_stat_replication.replay_lsn
     *
     * @mbg.generated
     */
    public void setReplayLsn(Object replayLsn) {
        this.replayLsn = replayLsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.write_lag
     *
     * @return the value of pg_stat_replication.write_lag
     *
     * @mbg.generated
     */
    public Object getWriteLag() {
        return writeLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.write_lag
     *
     * @param writeLag the value for pg_stat_replication.write_lag
     *
     * @mbg.generated
     */
    public void setWriteLag(Object writeLag) {
        this.writeLag = writeLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.flush_lag
     *
     * @return the value of pg_stat_replication.flush_lag
     *
     * @mbg.generated
     */
    public Object getFlushLag() {
        return flushLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.flush_lag
     *
     * @param flushLag the value for pg_stat_replication.flush_lag
     *
     * @mbg.generated
     */
    public void setFlushLag(Object flushLag) {
        this.flushLag = flushLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.replay_lag
     *
     * @return the value of pg_stat_replication.replay_lag
     *
     * @mbg.generated
     */
    public Object getReplayLag() {
        return replayLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.replay_lag
     *
     * @param replayLag the value for pg_stat_replication.replay_lag
     *
     * @mbg.generated
     */
    public void setReplayLag(Object replayLag) {
        this.replayLag = replayLag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.sync_priority
     *
     * @return the value of pg_stat_replication.sync_priority
     *
     * @mbg.generated
     */
    public Integer getSyncPriority() {
        return syncPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.sync_priority
     *
     * @param syncPriority the value for pg_stat_replication.sync_priority
     *
     * @mbg.generated
     */
    public void setSyncPriority(Integer syncPriority) {
        this.syncPriority = syncPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_replication.sync_state
     *
     * @return the value of pg_stat_replication.sync_state
     *
     * @mbg.generated
     */
    public String getSyncState() {
        return syncState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_replication.sync_state
     *
     * @param syncState the value for pg_stat_replication.sync_state
     *
     * @mbg.generated
     */
    public void setSyncState(String syncState) {
        this.syncState = syncState == null ? null : syncState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_replication
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", usesysid=").append(usesysid);
        sb.append(", usename=").append(usename);
        sb.append(", applicationName=").append(applicationName);
        sb.append(", clientAddr=").append(clientAddr);
        sb.append(", clientHostname=").append(clientHostname);
        sb.append(", clientPort=").append(clientPort);
        sb.append(", backendStart=").append(backendStart);
        sb.append(", backendXmin=").append(backendXmin);
        sb.append(", state=").append(state);
        sb.append(", sentLsn=").append(sentLsn);
        sb.append(", writeLsn=").append(writeLsn);
        sb.append(", flushLsn=").append(flushLsn);
        sb.append(", replayLsn=").append(replayLsn);
        sb.append(", writeLag=").append(writeLag);
        sb.append(", flushLag=").append(flushLag);
        sb.append(", replayLag=").append(replayLag);
        sb.append(", syncPriority=").append(syncPriority);
        sb.append(", syncState=").append(syncState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}