package com.alva.arbook.entity;

import java.io.Serializable;

public class PgStatSsl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.ssl
     *
     * @mbg.generated
     */
    private Boolean ssl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.cipher
     *
     * @mbg.generated
     */
    private String cipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.bits
     *
     * @mbg.generated
     */
    private Integer bits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.compression
     *
     * @mbg.generated
     */
    private Boolean compression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_stat_ssl.clientdn
     *
     * @mbg.generated
     */
    private String clientdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_stat_ssl
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.pid
     *
     * @return the value of pg_stat_ssl.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.pid
     *
     * @param pid the value for pg_stat_ssl.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.ssl
     *
     * @return the value of pg_stat_ssl.ssl
     *
     * @mbg.generated
     */
    public Boolean getSsl() {
        return ssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.ssl
     *
     * @param ssl the value for pg_stat_ssl.ssl
     *
     * @mbg.generated
     */
    public void setSsl(Boolean ssl) {
        this.ssl = ssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.version
     *
     * @return the value of pg_stat_ssl.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.version
     *
     * @param version the value for pg_stat_ssl.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.cipher
     *
     * @return the value of pg_stat_ssl.cipher
     *
     * @mbg.generated
     */
    public String getCipher() {
        return cipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.cipher
     *
     * @param cipher the value for pg_stat_ssl.cipher
     *
     * @mbg.generated
     */
    public void setCipher(String cipher) {
        this.cipher = cipher == null ? null : cipher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.bits
     *
     * @return the value of pg_stat_ssl.bits
     *
     * @mbg.generated
     */
    public Integer getBits() {
        return bits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.bits
     *
     * @param bits the value for pg_stat_ssl.bits
     *
     * @mbg.generated
     */
    public void setBits(Integer bits) {
        this.bits = bits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.compression
     *
     * @return the value of pg_stat_ssl.compression
     *
     * @mbg.generated
     */
    public Boolean getCompression() {
        return compression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.compression
     *
     * @param compression the value for pg_stat_ssl.compression
     *
     * @mbg.generated
     */
    public void setCompression(Boolean compression) {
        this.compression = compression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_stat_ssl.clientdn
     *
     * @return the value of pg_stat_ssl.clientdn
     *
     * @mbg.generated
     */
    public String getClientdn() {
        return clientdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_stat_ssl.clientdn
     *
     * @param clientdn the value for pg_stat_ssl.clientdn
     *
     * @mbg.generated
     */
    public void setClientdn(String clientdn) {
        this.clientdn = clientdn == null ? null : clientdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_stat_ssl
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", ssl=").append(ssl);
        sb.append(", version=").append(version);
        sb.append(", cipher=").append(cipher);
        sb.append(", bits=").append(bits);
        sb.append(", compression=").append(compression);
        sb.append(", clientdn=").append(clientdn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}