package com.alva.arbook.entity;

import java.io.Serializable;

public class PgSubscription implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subdbid
     *
     * @mbg.generated
     */
    private Long subdbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subname
     *
     * @mbg.generated
     */
    private String subname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subowner
     *
     * @mbg.generated
     */
    private Long subowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subenabled
     *
     * @mbg.generated
     */
    private Boolean subenabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subconninfo
     *
     * @mbg.generated
     */
    private String subconninfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subslotname
     *
     * @mbg.generated
     */
    private String subslotname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subsynccommit
     *
     * @mbg.generated
     */
    private String subsynccommit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_subscription.subpublications
     *
     * @mbg.generated
     */
    private Object subpublications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_subscription
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subdbid
     *
     * @return the value of pg_subscription.subdbid
     *
     * @mbg.generated
     */
    public Long getSubdbid() {
        return subdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subdbid
     *
     * @param subdbid the value for pg_subscription.subdbid
     *
     * @mbg.generated
     */
    public void setSubdbid(Long subdbid) {
        this.subdbid = subdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subname
     *
     * @return the value of pg_subscription.subname
     *
     * @mbg.generated
     */
    public String getSubname() {
        return subname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subname
     *
     * @param subname the value for pg_subscription.subname
     *
     * @mbg.generated
     */
    public void setSubname(String subname) {
        this.subname = subname == null ? null : subname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subowner
     *
     * @return the value of pg_subscription.subowner
     *
     * @mbg.generated
     */
    public Long getSubowner() {
        return subowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subowner
     *
     * @param subowner the value for pg_subscription.subowner
     *
     * @mbg.generated
     */
    public void setSubowner(Long subowner) {
        this.subowner = subowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subenabled
     *
     * @return the value of pg_subscription.subenabled
     *
     * @mbg.generated
     */
    public Boolean getSubenabled() {
        return subenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subenabled
     *
     * @param subenabled the value for pg_subscription.subenabled
     *
     * @mbg.generated
     */
    public void setSubenabled(Boolean subenabled) {
        this.subenabled = subenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subconninfo
     *
     * @return the value of pg_subscription.subconninfo
     *
     * @mbg.generated
     */
    public String getSubconninfo() {
        return subconninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subconninfo
     *
     * @param subconninfo the value for pg_subscription.subconninfo
     *
     * @mbg.generated
     */
    public void setSubconninfo(String subconninfo) {
        this.subconninfo = subconninfo == null ? null : subconninfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subslotname
     *
     * @return the value of pg_subscription.subslotname
     *
     * @mbg.generated
     */
    public String getSubslotname() {
        return subslotname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subslotname
     *
     * @param subslotname the value for pg_subscription.subslotname
     *
     * @mbg.generated
     */
    public void setSubslotname(String subslotname) {
        this.subslotname = subslotname == null ? null : subslotname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subsynccommit
     *
     * @return the value of pg_subscription.subsynccommit
     *
     * @mbg.generated
     */
    public String getSubsynccommit() {
        return subsynccommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subsynccommit
     *
     * @param subsynccommit the value for pg_subscription.subsynccommit
     *
     * @mbg.generated
     */
    public void setSubsynccommit(String subsynccommit) {
        this.subsynccommit = subsynccommit == null ? null : subsynccommit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_subscription.subpublications
     *
     * @return the value of pg_subscription.subpublications
     *
     * @mbg.generated
     */
    public Object getSubpublications() {
        return subpublications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_subscription.subpublications
     *
     * @param subpublications the value for pg_subscription.subpublications
     *
     * @mbg.generated
     */
    public void setSubpublications(Object subpublications) {
        this.subpublications = subpublications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_subscription
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subdbid=").append(subdbid);
        sb.append(", subname=").append(subname);
        sb.append(", subowner=").append(subowner);
        sb.append(", subenabled=").append(subenabled);
        sb.append(", subconninfo=").append(subconninfo);
        sb.append(", subslotname=").append(subslotname);
        sb.append(", subsynccommit=").append(subsynccommit);
        sb.append(", subpublications=").append(subpublications);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}