package com.alva.arbook.entity;

import java.io.Serializable;

public class PgTsConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_ts_config.cfgname
     *
     * @mbg.generated
     */
    private String cfgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_ts_config.cfgnamespace
     *
     * @mbg.generated
     */
    private Long cfgnamespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_ts_config.cfgowner
     *
     * @mbg.generated
     */
    private Long cfgowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_ts_config.cfgparser
     *
     * @mbg.generated
     */
    private Long cfgparser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_ts_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_ts_config.cfgname
     *
     * @return the value of pg_ts_config.cfgname
     *
     * @mbg.generated
     */
    public String getCfgname() {
        return cfgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_ts_config.cfgname
     *
     * @param cfgname the value for pg_ts_config.cfgname
     *
     * @mbg.generated
     */
    public void setCfgname(String cfgname) {
        this.cfgname = cfgname == null ? null : cfgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_ts_config.cfgnamespace
     *
     * @return the value of pg_ts_config.cfgnamespace
     *
     * @mbg.generated
     */
    public Long getCfgnamespace() {
        return cfgnamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_ts_config.cfgnamespace
     *
     * @param cfgnamespace the value for pg_ts_config.cfgnamespace
     *
     * @mbg.generated
     */
    public void setCfgnamespace(Long cfgnamespace) {
        this.cfgnamespace = cfgnamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_ts_config.cfgowner
     *
     * @return the value of pg_ts_config.cfgowner
     *
     * @mbg.generated
     */
    public Long getCfgowner() {
        return cfgowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_ts_config.cfgowner
     *
     * @param cfgowner the value for pg_ts_config.cfgowner
     *
     * @mbg.generated
     */
    public void setCfgowner(Long cfgowner) {
        this.cfgowner = cfgowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_ts_config.cfgparser
     *
     * @return the value of pg_ts_config.cfgparser
     *
     * @mbg.generated
     */
    public Long getCfgparser() {
        return cfgparser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_ts_config.cfgparser
     *
     * @param cfgparser the value for pg_ts_config.cfgparser
     *
     * @mbg.generated
     */
    public void setCfgparser(Long cfgparser) {
        this.cfgparser = cfgparser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_ts_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cfgname=").append(cfgname);
        sb.append(", cfgnamespace=").append(cfgnamespace);
        sb.append(", cfgowner=").append(cfgowner);
        sb.append(", cfgparser=").append(cfgparser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}