package com.alva.arbook.entity;

import java.io.Serializable;

public class PgUserMapping implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_user_mapping.umuser
     *
     * @mbg.generated
     */
    private Long umuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_user_mapping.umserver
     *
     * @mbg.generated
     */
    private Long umserver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_user_mapping.umoptions
     *
     * @mbg.generated
     */
    private Object umoptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_user_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_user_mapping.umuser
     *
     * @return the value of pg_user_mapping.umuser
     *
     * @mbg.generated
     */
    public Long getUmuser() {
        return umuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_user_mapping.umuser
     *
     * @param umuser the value for pg_user_mapping.umuser
     *
     * @mbg.generated
     */
    public void setUmuser(Long umuser) {
        this.umuser = umuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_user_mapping.umserver
     *
     * @return the value of pg_user_mapping.umserver
     *
     * @mbg.generated
     */
    public Long getUmserver() {
        return umserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_user_mapping.umserver
     *
     * @param umserver the value for pg_user_mapping.umserver
     *
     * @mbg.generated
     */
    public void setUmserver(Long umserver) {
        this.umserver = umserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_user_mapping.umoptions
     *
     * @return the value of pg_user_mapping.umoptions
     *
     * @mbg.generated
     */
    public Object getUmoptions() {
        return umoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_user_mapping.umoptions
     *
     * @param umoptions the value for pg_user_mapping.umoptions
     *
     * @mbg.generated
     */
    public void setUmoptions(Object umoptions) {
        this.umoptions = umoptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_user_mapping
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", umuser=").append(umuser);
        sb.append(", umserver=").append(umserver);
        sb.append(", umoptions=").append(umoptions);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}