package com.alva.arbook.entity;

import java.io.Serializable;

public class PgViews implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_views.schemaname
     *
     * @mbg.generated
     */
    private String schemaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_views.viewname
     *
     * @mbg.generated
     */
    private String viewname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_views.viewowner
     *
     * @mbg.generated
     */
    private String viewowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pg_views.definition
     *
     * @mbg.generated
     */
    private String definition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pg_views
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_views.schemaname
     *
     * @return the value of pg_views.schemaname
     *
     * @mbg.generated
     */
    public String getSchemaname() {
        return schemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_views.schemaname
     *
     * @param schemaname the value for pg_views.schemaname
     *
     * @mbg.generated
     */
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname == null ? null : schemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_views.viewname
     *
     * @return the value of pg_views.viewname
     *
     * @mbg.generated
     */
    public String getViewname() {
        return viewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_views.viewname
     *
     * @param viewname the value for pg_views.viewname
     *
     * @mbg.generated
     */
    public void setViewname(String viewname) {
        this.viewname = viewname == null ? null : viewname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_views.viewowner
     *
     * @return the value of pg_views.viewowner
     *
     * @mbg.generated
     */
    public String getViewowner() {
        return viewowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_views.viewowner
     *
     * @param viewowner the value for pg_views.viewowner
     *
     * @mbg.generated
     */
    public void setViewowner(String viewowner) {
        this.viewowner = viewowner == null ? null : viewowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pg_views.definition
     *
     * @return the value of pg_views.definition
     *
     * @mbg.generated
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pg_views.definition
     *
     * @param definition the value for pg_views.definition
     *
     * @mbg.generated
     */
    public void setDefinition(String definition) {
        this.definition = definition == null ? null : definition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pg_views
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schemaname=").append(schemaname);
        sb.append(", viewname=").append(viewname);
        sb.append(", viewowner=").append(viewowner);
        sb.append(", definition=").append(definition);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}