package com.alva.arbook.entity;

import java.io.Serializable;

public class RoleUsageGrants implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.grantor
     *
     * @mbg.generated
     */
    private Object grantor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.grantee
     *
     * @mbg.generated
     */
    private Object grantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.object_catalog
     *
     * @mbg.generated
     */
    private Object objectCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.object_schema
     *
     * @mbg.generated
     */
    private Object objectSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.object_name
     *
     * @mbg.generated
     */
    private Object objectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.object_type
     *
     * @mbg.generated
     */
    private Object objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.privilege_type
     *
     * @mbg.generated
     */
    private Object privilegeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_usage_grants.is_grantable
     *
     * @mbg.generated
     */
    private Object isGrantable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_usage_grants
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.grantor
     *
     * @return the value of role_usage_grants.grantor
     *
     * @mbg.generated
     */
    public Object getGrantor() {
        return grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.grantor
     *
     * @param grantor the value for role_usage_grants.grantor
     *
     * @mbg.generated
     */
    public void setGrantor(Object grantor) {
        this.grantor = grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.grantee
     *
     * @return the value of role_usage_grants.grantee
     *
     * @mbg.generated
     */
    public Object getGrantee() {
        return grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.grantee
     *
     * @param grantee the value for role_usage_grants.grantee
     *
     * @mbg.generated
     */
    public void setGrantee(Object grantee) {
        this.grantee = grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.object_catalog
     *
     * @return the value of role_usage_grants.object_catalog
     *
     * @mbg.generated
     */
    public Object getObjectCatalog() {
        return objectCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.object_catalog
     *
     * @param objectCatalog the value for role_usage_grants.object_catalog
     *
     * @mbg.generated
     */
    public void setObjectCatalog(Object objectCatalog) {
        this.objectCatalog = objectCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.object_schema
     *
     * @return the value of role_usage_grants.object_schema
     *
     * @mbg.generated
     */
    public Object getObjectSchema() {
        return objectSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.object_schema
     *
     * @param objectSchema the value for role_usage_grants.object_schema
     *
     * @mbg.generated
     */
    public void setObjectSchema(Object objectSchema) {
        this.objectSchema = objectSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.object_name
     *
     * @return the value of role_usage_grants.object_name
     *
     * @mbg.generated
     */
    public Object getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.object_name
     *
     * @param objectName the value for role_usage_grants.object_name
     *
     * @mbg.generated
     */
    public void setObjectName(Object objectName) {
        this.objectName = objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.object_type
     *
     * @return the value of role_usage_grants.object_type
     *
     * @mbg.generated
     */
    public Object getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.object_type
     *
     * @param objectType the value for role_usage_grants.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(Object objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.privilege_type
     *
     * @return the value of role_usage_grants.privilege_type
     *
     * @mbg.generated
     */
    public Object getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.privilege_type
     *
     * @param privilegeType the value for role_usage_grants.privilege_type
     *
     * @mbg.generated
     */
    public void setPrivilegeType(Object privilegeType) {
        this.privilegeType = privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_usage_grants.is_grantable
     *
     * @return the value of role_usage_grants.is_grantable
     *
     * @mbg.generated
     */
    public Object getIsGrantable() {
        return isGrantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_usage_grants.is_grantable
     *
     * @param isGrantable the value for role_usage_grants.is_grantable
     *
     * @mbg.generated
     */
    public void setIsGrantable(Object isGrantable) {
        this.isGrantable = isGrantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usage_grants
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", grantor=").append(grantor);
        sb.append(", grantee=").append(grantee);
        sb.append(", objectCatalog=").append(objectCatalog);
        sb.append(", objectSchema=").append(objectSchema);
        sb.append(", objectName=").append(objectName);
        sb.append(", objectType=").append(objectType);
        sb.append(", privilegeType=").append(privilegeType);
        sb.append(", isGrantable=").append(isGrantable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}