package com.alva.arbook.entity;

import java.io.Serializable;

public class Sequences implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.sequence_catalog
     *
     * @mbg.generated
     */
    private Object sequenceCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.sequence_schema
     *
     * @mbg.generated
     */
    private Object sequenceSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.sequence_name
     *
     * @mbg.generated
     */
    private Object sequenceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.data_type
     *
     * @mbg.generated
     */
    private Object dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.numeric_precision
     *
     * @mbg.generated
     */
    private Object numericPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.numeric_precision_radix
     *
     * @mbg.generated
     */
    private Object numericPrecisionRadix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.numeric_scale
     *
     * @mbg.generated
     */
    private Object numericScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.start_value
     *
     * @mbg.generated
     */
    private Object startValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.minimum_value
     *
     * @mbg.generated
     */
    private Object minimumValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.maximum_value
     *
     * @mbg.generated
     */
    private Object maximumValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.increment
     *
     * @mbg.generated
     */
    private Object increment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.cycle_option
     *
     * @mbg.generated
     */
    private Object cycleOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sequences
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.sequence_catalog
     *
     * @return the value of sequences.sequence_catalog
     *
     * @mbg.generated
     */
    public Object getSequenceCatalog() {
        return sequenceCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.sequence_catalog
     *
     * @param sequenceCatalog the value for sequences.sequence_catalog
     *
     * @mbg.generated
     */
    public void setSequenceCatalog(Object sequenceCatalog) {
        this.sequenceCatalog = sequenceCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.sequence_schema
     *
     * @return the value of sequences.sequence_schema
     *
     * @mbg.generated
     */
    public Object getSequenceSchema() {
        return sequenceSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.sequence_schema
     *
     * @param sequenceSchema the value for sequences.sequence_schema
     *
     * @mbg.generated
     */
    public void setSequenceSchema(Object sequenceSchema) {
        this.sequenceSchema = sequenceSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.sequence_name
     *
     * @return the value of sequences.sequence_name
     *
     * @mbg.generated
     */
    public Object getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.sequence_name
     *
     * @param sequenceName the value for sequences.sequence_name
     *
     * @mbg.generated
     */
    public void setSequenceName(Object sequenceName) {
        this.sequenceName = sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.data_type
     *
     * @return the value of sequences.data_type
     *
     * @mbg.generated
     */
    public Object getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.data_type
     *
     * @param dataType the value for sequences.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Object dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.numeric_precision
     *
     * @return the value of sequences.numeric_precision
     *
     * @mbg.generated
     */
    public Object getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.numeric_precision
     *
     * @param numericPrecision the value for sequences.numeric_precision
     *
     * @mbg.generated
     */
    public void setNumericPrecision(Object numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.numeric_precision_radix
     *
     * @return the value of sequences.numeric_precision_radix
     *
     * @mbg.generated
     */
    public Object getNumericPrecisionRadix() {
        return numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.numeric_precision_radix
     *
     * @param numericPrecisionRadix the value for sequences.numeric_precision_radix
     *
     * @mbg.generated
     */
    public void setNumericPrecisionRadix(Object numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.numeric_scale
     *
     * @return the value of sequences.numeric_scale
     *
     * @mbg.generated
     */
    public Object getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.numeric_scale
     *
     * @param numericScale the value for sequences.numeric_scale
     *
     * @mbg.generated
     */
    public void setNumericScale(Object numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.start_value
     *
     * @return the value of sequences.start_value
     *
     * @mbg.generated
     */
    public Object getStartValue() {
        return startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.start_value
     *
     * @param startValue the value for sequences.start_value
     *
     * @mbg.generated
     */
    public void setStartValue(Object startValue) {
        this.startValue = startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.minimum_value
     *
     * @return the value of sequences.minimum_value
     *
     * @mbg.generated
     */
    public Object getMinimumValue() {
        return minimumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.minimum_value
     *
     * @param minimumValue the value for sequences.minimum_value
     *
     * @mbg.generated
     */
    public void setMinimumValue(Object minimumValue) {
        this.minimumValue = minimumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.maximum_value
     *
     * @return the value of sequences.maximum_value
     *
     * @mbg.generated
     */
    public Object getMaximumValue() {
        return maximumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.maximum_value
     *
     * @param maximumValue the value for sequences.maximum_value
     *
     * @mbg.generated
     */
    public void setMaximumValue(Object maximumValue) {
        this.maximumValue = maximumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.increment
     *
     * @return the value of sequences.increment
     *
     * @mbg.generated
     */
    public Object getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.increment
     *
     * @param increment the value for sequences.increment
     *
     * @mbg.generated
     */
    public void setIncrement(Object increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.cycle_option
     *
     * @return the value of sequences.cycle_option
     *
     * @mbg.generated
     */
    public Object getCycleOption() {
        return cycleOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.cycle_option
     *
     * @param cycleOption the value for sequences.cycle_option
     *
     * @mbg.generated
     */
    public void setCycleOption(Object cycleOption) {
        this.cycleOption = cycleOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sequenceCatalog=").append(sequenceCatalog);
        sb.append(", sequenceSchema=").append(sequenceSchema);
        sb.append(", sequenceName=").append(sequenceName);
        sb.append(", dataType=").append(dataType);
        sb.append(", numericPrecision=").append(numericPrecision);
        sb.append(", numericPrecisionRadix=").append(numericPrecisionRadix);
        sb.append(", numericScale=").append(numericScale);
        sb.append(", startValue=").append(startValue);
        sb.append(", minimumValue=").append(minimumValue);
        sb.append(", maximumValue=").append(maximumValue);
        sb.append(", increment=").append(increment);
        sb.append(", cycleOption=").append(cycleOption);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}