package com.alva.arbook.entity;

import java.io.Serializable;

public class SqlImplementationInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_implementation_info.implementation_info_id
     *
     * @mbg.generated
     */
    private Object implementationInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_implementation_info.implementation_info_name
     *
     * @mbg.generated
     */
    private Object implementationInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_implementation_info.integer_value
     *
     * @mbg.generated
     */
    private Object integerValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_implementation_info.character_value
     *
     * @mbg.generated
     */
    private Object characterValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_implementation_info.comments
     *
     * @mbg.generated
     */
    private Object comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sql_implementation_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_implementation_info.implementation_info_id
     *
     * @return the value of sql_implementation_info.implementation_info_id
     *
     * @mbg.generated
     */
    public Object getImplementationInfoId() {
        return implementationInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_implementation_info.implementation_info_id
     *
     * @param implementationInfoId the value for sql_implementation_info.implementation_info_id
     *
     * @mbg.generated
     */
    public void setImplementationInfoId(Object implementationInfoId) {
        this.implementationInfoId = implementationInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_implementation_info.implementation_info_name
     *
     * @return the value of sql_implementation_info.implementation_info_name
     *
     * @mbg.generated
     */
    public Object getImplementationInfoName() {
        return implementationInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_implementation_info.implementation_info_name
     *
     * @param implementationInfoName the value for sql_implementation_info.implementation_info_name
     *
     * @mbg.generated
     */
    public void setImplementationInfoName(Object implementationInfoName) {
        this.implementationInfoName = implementationInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_implementation_info.integer_value
     *
     * @return the value of sql_implementation_info.integer_value
     *
     * @mbg.generated
     */
    public Object getIntegerValue() {
        return integerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_implementation_info.integer_value
     *
     * @param integerValue the value for sql_implementation_info.integer_value
     *
     * @mbg.generated
     */
    public void setIntegerValue(Object integerValue) {
        this.integerValue = integerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_implementation_info.character_value
     *
     * @return the value of sql_implementation_info.character_value
     *
     * @mbg.generated
     */
    public Object getCharacterValue() {
        return characterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_implementation_info.character_value
     *
     * @param characterValue the value for sql_implementation_info.character_value
     *
     * @mbg.generated
     */
    public void setCharacterValue(Object characterValue) {
        this.characterValue = characterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_implementation_info.comments
     *
     * @return the value of sql_implementation_info.comments
     *
     * @mbg.generated
     */
    public Object getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_implementation_info.comments
     *
     * @param comments the value for sql_implementation_info.comments
     *
     * @mbg.generated
     */
    public void setComments(Object comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_implementation_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", implementationInfoId=").append(implementationInfoId);
        sb.append(", implementationInfoName=").append(implementationInfoName);
        sb.append(", integerValue=").append(integerValue);
        sb.append(", characterValue=").append(characterValue);
        sb.append(", comments=").append(comments);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}