package com.alva.arbook.entity;

import java.io.Serializable;

public class SysSubjectT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_subject_t.sz_id
     *
     * @mbg.generated
     */
    private String szId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_subject_t.sz_caption
     *
     * @mbg.generated
     */
    private String szCaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_subject_t
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_subject_t.sz_id
     *
     * @return the value of sys_subject_t.sz_id
     * @mbg.generated
     */
    public String getSzId() {
        return szId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_subject_t.sz_id
     *
     * @param szId the value for sys_subject_t.sz_id
     * @mbg.generated
     */
    public void setSzId(String szId) {
        this.szId = szId == null ? null : szId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_subject_t.sz_caption
     *
     * @return the value of sys_subject_t.sz_caption
     * @mbg.generated
     */
    public String getSzCaption() {
        return szCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_subject_t.sz_caption
     *
     * @param szCaption the value for sys_subject_t.sz_caption
     * @mbg.generated
     */
    public void setSzCaption(String szCaption) {
        this.szCaption = szCaption == null ? null : szCaption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject_t
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", szId=").append(szId);
        sb.append(", szCaption=").append(szCaption);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}