package com.alva.arbook.entity;

import com.alva.arbook.annotation.DataName;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

public class SysUserT implements Serializable {

    private Integer szId;

    @NotNull
    @DataName(name = "邮箱")
    private String szEmail;

    @NotNull
    @DataName(name = "密码")
    private String szPassword;

    @DataName(name = "手机号")
    private String szPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_t.ts_created
     *
     * @mbg.generated
     */
    private Date tsCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_t.ts_updated
     *
     * @mbg.generated
     */
    private Date tsUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_t.nt_row_state
     *
     * @mbg.generated
     */
    private Integer ntRowState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_t.nt_row_version
     *
     * @mbg.generated
     */
    private Integer ntRowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_t
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.sz_id
     *
     * @return the value of sys_user_t.sz_id
     * @mbg.generated
     */
    public Integer getSzId() {
        return szId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.sz_id
     *
     * @param szId the value for sys_user_t.sz_id
     * @mbg.generated
     */
    public void setSzId(Integer szId) {
        this.szId = szId == null ? null : szId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.sz_email
     *
     * @return the value of sys_user_t.sz_email
     * @mbg.generated
     */
    public String getSzEmail() {
        return szEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.sz_email
     *
     * @param szEmail the value for sys_user_t.sz_email
     * @mbg.generated
     */
    public void setSzEmail(String szEmail) {
        this.szEmail = szEmail == null ? null : szEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.sz_password
     *
     * @return the value of sys_user_t.sz_password
     * @mbg.generated
     */
    public String getSzPassword() {
        return szPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.sz_password
     *
     * @param szPassword the value for sys_user_t.sz_password
     * @mbg.generated
     */
    public void setSzPassword(String szPassword) {
        this.szPassword = szPassword == null ? null : szPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.sz_phone
     *
     * @return the value of sys_user_t.sz_phone
     * @mbg.generated
     */
    public String getSzPhone() {
        return szPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.sz_phone
     *
     * @param szPhone the value for sys_user_t.sz_phone
     * @mbg.generated
     */
    public void setSzPhone(String szPhone) {
        this.szPhone = szPhone == null ? null : szPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.ts_created
     *
     * @return the value of sys_user_t.ts_created
     * @mbg.generated
     */
    public Date getTsCreated() {
        return tsCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.ts_created
     *
     * @param tsCreated the value for sys_user_t.ts_created
     * @mbg.generated
     */
    public void setTsCreated(Date tsCreated) {
        this.tsCreated = tsCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.ts_updated
     *
     * @return the value of sys_user_t.ts_updated
     * @mbg.generated
     */
    public Date getTsUpdated() {
        return tsUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.ts_updated
     *
     * @param tsUpdated the value for sys_user_t.ts_updated
     * @mbg.generated
     */
    public void setTsUpdated(Date tsUpdated) {
        this.tsUpdated = tsUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.nt_row_state
     *
     * @return the value of sys_user_t.nt_row_state
     * @mbg.generated
     */
    public Integer getNtRowState() {
        return ntRowState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.nt_row_state
     *
     * @param ntRowState the value for sys_user_t.nt_row_state
     * @mbg.generated
     */
    public void setNtRowState(Integer ntRowState) {
        this.ntRowState = ntRowState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_t.nt_row_version
     *
     * @return the value of sys_user_t.nt_row_version
     * @mbg.generated
     */
    public Integer getNtRowVersion() {
        return ntRowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_t.nt_row_version
     *
     * @param ntRowVersion the value for sys_user_t.nt_row_version
     * @mbg.generated
     */
    public void setNtRowVersion(Integer ntRowVersion) {
        this.ntRowVersion = ntRowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", szId=").append(szId);
        sb.append(", szEmail=").append(szEmail);
        sb.append(", szPassword=").append(szPassword);
        sb.append(", szPhone=").append(szPhone);
        sb.append(", tsCreated=").append(tsCreated);
        sb.append(", tsUpdated=").append(tsUpdated);
        sb.append(", ntRowState=").append(ntRowState);
        sb.append(", ntRowVersion=").append(ntRowVersion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}