package com.alva.arbook.entity;

import java.io.Serializable;

public class ViewRoutineUsage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.table_catalog
     *
     * @mbg.generated
     */
    private Object tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.table_schema
     *
     * @mbg.generated
     */
    private Object tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.table_name
     *
     * @mbg.generated
     */
    private Object tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.specific_catalog
     *
     * @mbg.generated
     */
    private Object specificCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.specific_schema
     *
     * @mbg.generated
     */
    private Object specificSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_routine_usage.specific_name
     *
     * @mbg.generated
     */
    private Object specificName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_routine_usage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.table_catalog
     *
     * @return the value of view_routine_usage.table_catalog
     *
     * @mbg.generated
     */
    public Object getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.table_catalog
     *
     * @param tableCatalog the value for view_routine_usage.table_catalog
     *
     * @mbg.generated
     */
    public void setTableCatalog(Object tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.table_schema
     *
     * @return the value of view_routine_usage.table_schema
     *
     * @mbg.generated
     */
    public Object getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.table_schema
     *
     * @param tableSchema the value for view_routine_usage.table_schema
     *
     * @mbg.generated
     */
    public void setTableSchema(Object tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.table_name
     *
     * @return the value of view_routine_usage.table_name
     *
     * @mbg.generated
     */
    public Object getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.table_name
     *
     * @param tableName the value for view_routine_usage.table_name
     *
     * @mbg.generated
     */
    public void setTableName(Object tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.specific_catalog
     *
     * @return the value of view_routine_usage.specific_catalog
     *
     * @mbg.generated
     */
    public Object getSpecificCatalog() {
        return specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.specific_catalog
     *
     * @param specificCatalog the value for view_routine_usage.specific_catalog
     *
     * @mbg.generated
     */
    public void setSpecificCatalog(Object specificCatalog) {
        this.specificCatalog = specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.specific_schema
     *
     * @return the value of view_routine_usage.specific_schema
     *
     * @mbg.generated
     */
    public Object getSpecificSchema() {
        return specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.specific_schema
     *
     * @param specificSchema the value for view_routine_usage.specific_schema
     *
     * @mbg.generated
     */
    public void setSpecificSchema(Object specificSchema) {
        this.specificSchema = specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_routine_usage.specific_name
     *
     * @return the value of view_routine_usage.specific_name
     *
     * @mbg.generated
     */
    public Object getSpecificName() {
        return specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_routine_usage.specific_name
     *
     * @param specificName the value for view_routine_usage.specific_name
     *
     * @mbg.generated
     */
    public void setSpecificName(Object specificName) {
        this.specificName = specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_routine_usage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tableCatalog=").append(tableCatalog);
        sb.append(", tableSchema=").append(tableSchema);
        sb.append(", tableName=").append(tableName);
        sb.append(", specificCatalog=").append(specificCatalog);
        sb.append(", specificSchema=").append(specificSchema);
        sb.append(", specificName=").append(specificName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}